### ISSUE TITLE
qgep plugin run problem 

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#122]
Hi,

I was just trying to replicate your setup and I thought that just by copying the qgep plugin into the qgis plugins directory would work but it throws me the following error:
Couldn't load plugin qgepplugin due to an error when calling its classFactory() method

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/web/.qgis2/python/plugins/qgepplugin/__init__.py", line 31, in classFactory
    from qgepplugin import QgepPlugin
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/web/.qgis2/python/plugins/qgepplugin/qgepplugin.py", line 28, in 
    import resources #@UnusedImport needed to make icons etc. appear
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named resources

Shouldn't it have worked by default?
The data model creation ran ok.

Really nice project,
Hope to join it soon.

Tudor

**Comment by m-kuhn** [comment]
Hi, you need to call `make` to compile the resources
