### ISSUE TITLE
crash of data entry in 0.5.5

### ISSUE THREAD

**Issue by oliver-ch** [QGEP/QGEP#124]
plugin: 0.5.5
qgep_en.qgs
on most recent db.dump

* Python Error 1 :after klicking 'Start Data Entry'

An error occured during execution of following code:
qgepplugin.ui.forms.vw_cover_open( _qgis_featureform_0, _qgis_layer_vw_qgep_cover, _qgis_feature_20150616152835836)

Traceback (most recent call last):
  File "", line 1, in 
  File "C:/Users/oliver.schweizer/.qgis2/python/plugins\qgepplugin\ui\forms.py", line 100, in vw_cover_open
    cover_ws_type_changed(form, feature, layer)
  File "C:/Users/oliver.schweizer/.qgis2/python/plugins\qgepplugin\ui\forms.py", line 71, in cover_ws_type_changed
    ws_type = ws_type_selector.property('EWV2Wrapper').value()
TypeError: unable to convert a C++ 'QgsWidgetWrapper*' instance to a Python object

* Python Error 2 and crash of entry: when selecting the ws_type

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/Users/oliver.schweizer/.qgis2/python/plugins\qgepplugin\ui\forms.py", line 97, in 
    lambda: cover_ws_type_changed(form, feature, layer)
  File "C:/Users/oliver.schweizer/.qgis2/python/plugins\qgepplugin\ui\forms.py", line 71, in cover_ws_type_changed
    ws_type = ws_type_selector.property('EWV2Wrapper').value()
TypeError: unable to convert a C++ 'QgsWidgetWrapper*' instance to a Python object

**Comment by m-kuhn** [comment]
Which QGIS version are you using?

**Comment by m-kuhn** [comment]
This feature needs a recent nightly build, i.e. 2.8 is not sufficient.

**Comment by oliver-ch** [comment]
it was 2.8.
