### ISSUE TITLE
Python errors on opening demodata project

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#390]
New problem with version 2.18.15 of qgis: 
![python_error_demoprojekt](https://user-images.githubusercontent.com/1265865/34735383-8fcc9934-f56f-11e7-937c-96cab0045dfe.jpg)

2018-01-09T18:19:08	1	Traceback (most recent call last):
			  File "C:/Users/stefan/.qgis2/python/plugins\qgepplugin\qgepplugin.py", line 289, in onLayersAvailable
			    self.network_analyzer.setNodeLayer(layers['vw_network_node'])
			  File "C:/Users/stefan/.qgis2/python/plugins\qgepplugin\tools\qgepnetwork.py", line 107, in setNodeLayer
			    self.createGraph()
			  File "C:/Users/stefan/.qgis2/python/plugins\qgepplugin\tools\qgepnetwork.py", line 229, in createGraph
			    self._addVertices()
			  File "C:/Users/stefan/.qgis2/python/plugins\qgepplugin\tools\qgepnetwork.py", line 129, in _addVertices
			    self.graph.add_node(fid, dict(point=vertex, objType=obj_type, objId=obj_id))
			TypeError: add_node() takes exactly 2 arguments (3 given)

Processing:
2018-01-09T18:18:04	2	Problem with SAGA installation: unsupported SAGA version found.
  
Python warnings:
2018-01-09T18:18:03	1	warning:C:\OSGEO4~1\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py:844: PendingDeprecationWarning: This method will be removed in future versions.  Use 'elem.iter()' or 'list(elem.iter())' instead.
			  for include in elem.getiterator("include"):
			
			traceback:  File "<string>", line 1, in <module>
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/stefan/.qgis2/python/plugins\interlis\__init__.py", line 27, in classFactory
			    from interlis import Interlis
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/stefan/.qgis2/python/plugins\interlis\interlis.py", line 29, in <module>
			    from processing.core.Processing import Processing
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\__init__.py", line 29, in <module>
			    from processing.tools.general import *              # NOQA
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\tools\general.py", line 31, in <module>
			    from processing.core.Processing import Processing
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\core\Processing.py", line 46, in <module>
			    from processing.gui.MessageBarProgress import MessageBarProgress
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\MessageBarProgress.py", line 32, in <module>
			    from processing.gui.MessageDialog import MessageDialog
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\MessageDialog.py", line 38, in <module>
			    os.path.join(pluginPath, 'ui', 'DlgMessage.ui'))
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\PyQt4\uic\__init__.py", line 210, in loadUiType
			    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix)
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\PyQt4\uic\Compiler\compiler.py", line 139, in compileUi
			    w = self.parse(input_stream, resource_suffix)
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py", line 933, in parse
			    actor(elem)
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py", line 844, in readResources
			    for include in elem.getiterator("include"):
			
2018-01-09T18:18:03	1	warning:C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py:607: ImportWarning: Not importing directory 'C:\OSGEO4~1\apps\Python27\lib\site-packages\win32\test': missing __init__.py
			  mod = _builtin_import(name, globals, locals, fromlist, level)
			
			traceback:  File "<string>", line 1, in <module>
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/stefan/.qgis2/python/plugins\interlis\__init__.py", line 27, in classFactory
			    from interlis import Interlis
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/stefan/.qgis2/python/plugins\interlis\interlis.py", line 29, in <module>
			    from processing.core.Processing import Processing
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\__init__.py", line 29, in <module>
			    from processing.tools.general import *              # NOQA
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\tools\general.py", line 31, in <module>
			    from processing.core.Processing import Processing
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\core\Processing.py", line 62, in <module>
			    from processing.algs.saga.SagaAlgorithmProvider import SagaAlgorithmProvider
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\saga\SagaAlgorithmProvider.py", line 33, in <module>
			    from SagaAlgorithm import SagaAlgorithm
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\saga\SagaAlgorithm.py", line 20, in <module>
			    standard_library.install_aliases()
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\future\standard_library\__init__.py", line 483, in install_aliases
			    import test
			
2018-01-09T18:18:04	1	warning:C:\OSGEO4~1\apps\Python27\lib\pkgutil.py:186: ImportWarning: Not importing directory 'C:\OSGEO4~1\apps\Python27\lib\site-packages\mpl_toolkits': missing __init__.py
			  file, filename, etc = imp.find_module(subname, path)
			
			traceback:  File "<string>", line 1, in <module>
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/stefan/.qgis2/python/plugins\qgepplugin\__init__.py", line 29, in classFactory
			    from qgepplugin import QgepPlugin
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/stefan/.qgis2/python/plugins\qgepplugin\qgepplugin.py", line 49, in <module>
			    from tools.qgepnetwork import QgepGraphManager
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/stefan/.qgis2/python/plugins\qgepplugin\tools\qgepnetwork.py", line 54, in <module>
			    import networkx as nx
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\networkx\__init__.py", line 128, in <module>
			    import networkx.drawing
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\networkx\drawing\__init__.py", line 6, in <module>
			    from . import nx_pydot
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\networkx\drawing\nx_pydot.py", line 27, in <module>
			    from pkg_resources import parse_version
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "build\bdist.win-amd64\egg\pkg_resources.py", line 3027, in <module>
			    add_activation_listener(lambda dist: dist.activate())
			  File "build\bdist.win-amd64\egg\pkg_resources.py", line 741, in subscribe
			    callback(dist)
			  File "build\bdist.win-amd64\egg\pkg_resources.py", line 3027, in <lambda>
			    add_activation_listener(lambda dist: dist.activate())
			  File "build\bdist.win-amd64\egg\pkg_resources.py", line 2514, in activate
			    list(map(declare_namespace, self._get_metadata('namespace_packages.txt')))
			  File "build\bdist.win-amd64\egg\pkg_resources.py", line 2094, in declare_namespace
			    _handle_ns(packageName, path_item)
			  File "build\bdist.win-amd64\egg\pkg_resources.py", line 2051, in _handle_ns
			    loader = importer.find_module(packageName)
			
2018-01-09T18:18:04	1	warning:C:\OSGEO4~1\apps\Python27\lib\pkgutil.py:186: ImportWarning: Not importing directory 'c:\osgeo4~1\apps\python27\lib\site-packages\mpl_toolkits': missing __init__.py
			  file, filename, etc = imp.find_module(subname, path)
			
			traceback:  File "<string>", line 1, in <module>
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/stefan/.qgis2/python/plugins\qgepplugin\__init__.py", line 29, in classFactory
			    from qgepplugin import QgepPlugin
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/stefan/.qgis2/python/plugins\qgepplugin\qgepplugin.py", line 49, in <module>
			    from tools.qgepnetwork import QgepGraphManager
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/stefan/.qgis2/python/plugins\qgepplugin\tools\qgepnetwork.py", line 54, in <module>
			    import networkx as nx
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\networkx\__init__.py", line 128, in <module>
			    import networkx.drawing
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\networkx\drawing\__init__.py", line 6, in <module>
			    from . import nx_pydot
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\networkx\drawing\nx_pydot.py", line 27, in <module>
			    from pkg_resources import parse_version
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "build\bdist.win-amd64\egg\pkg_resources.py", line 3027, in <module>
			    add_activation_listener(lambda dist: dist.activate())
			  File "build\bdist.win-amd64\egg\pkg_resources.py", line 741, in subscribe
			    callback(dist)
			  File "build\bdist.win-amd64\egg\pkg_resources.py", line 3027, in <lambda>
			    add_activation_listener(lambda dist: dist.activate())
			  File "build\bdist.win-amd64\egg\pkg_resources.py", line 2513, in activate
			    fixup_namespace_packages(self.location)
			  File "build\bdist.win-amd64\egg\pkg_resources.py", line 2104, in fixup_namespace_packages
			    subpath = _handle_ns(package, path_item)
			  File "build\bdist.win-amd64\egg\pkg_resources.py", line 2051, in _handle_ns
			    loader = importer.find_module(packageName)

**Comment by sjib** [comment]
Network following tools now show up correctly but create python errors too.

**Comment by sjib** [comment]
https://github.com/QGEP/qgepplugin/issues/7
