### ISSUE TITLE
QGEP Plugin : Snapping issues when digitizing reaches

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#406]
When digitizing reaches with QGEP plugin editing wizard 

 - [x] QGIS visual snapping indicators are not shown 
 - [ ] Z coordinate is not taken into account (2D geometry is created)

**Expected behaviour**

![saisie_troncons](https://user-images.githubusercontent.com/8614223/37763426-53a6e1f2-2dbf-11e8-91fd-51894cd0f8b4.gif)

**Comment by m-kuhn** [comment]
Good point.

Can you confirm, this is for the plugin on 2.18?

**Comment by 3nids** [comment]
I guess my question is a bit silly, if we're digitizing reaches, then we speak about the altitude of nodes, correct?

**Comment by m-kuhn** [comment]
Using the node level sounds like the safest default to me :+1:

**Comment by ponceta** [comment]
Node is default yes.

**Comment by 3nids** [comment]
fixed in master, upcoming release

**Comment by lbartoletti** [comment]
Hi @3nids 

I have tested the plugin with your fix, some comments:

- Snapping indicator

Now, there is a snapping indicator, but it's not homogeneous:

When creating a reach, the markers differ from the QGIS2 standard. It uses the QGIS3 markers (inspired by autocad) but with errors:

A circle on a segment (not the QGIS3 standard)
![image](https://user-images.githubusercontent.com/7521540/41285297-006a5a9c-6e3c-11e8-812d-9b2129e678a7.png)

A square on a node, whereas the marker for the reach is the classic QGIS2 marker: a cross.
![image](https://user-images.githubusercontent.com/7521540/41285319-11c637ac-6e3c-11e8-98aa-96fe5f15b894.png)

moreover, the snapping for the reach does not respect the configuration of QGIS. It snaps on point or segment whatever the configuration.

It snaps even when the layer is not displayed
![image](https://user-images.githubusercontent.com/7521540/41285420-62f29cd8-6e3c-11e8-804c-160e49d0f20d.png)

And last point: cursors are not the same.

- Z support

Maybe, I misunderstood but I think the correction is not done.

Example, snapping from 1 to 2:

| wkt_geom | obj_id |
| -------- | ------ |
| CompoundCurveZ ((2749931.94053870067000389 1264510.58170946803875268 -0.01173122134059668, 2749992.03253880608826876 1264517.6117094773799181 -0.01173090003430843)) | ch13p7mzRE012511 |
| CompoundCurveZ ((2749936.44553871871903539 1264671.97970975353382528 -0.01173256896436214, 2749938.96753872698172927 1264732.68170985649339855 -0.01173307187855244)) | ch13p7mzRE012936 |

Formulaire:
![image](https://user-images.githubusercontent.com/7521540/41285599-f9a9282c-6e3c-11e8-8e23-98c350072eeb.png)

and the result

| wkt_geom | obj_id |
| -------- | ------ |
| CompoundCurveZ ((2749931.94053999986499548 1264510.58171000005677342 0, 2749936.44554000021889806 1264671.97971000010147691 0)) | 00000000RE017261 |

The Z is 0

cc @ponceta

**Comment by m-kuhn** [comment]
Thanks for testing @lbartoletti 

> moreover, the snapping for the reach does not respect the configuration of QGIS. It snaps on point or segment whatever the configuration.

Just a quick feedback on this point, the tool does not work on geometry types but on topology elements. The snapping happens on *wastewater nodes* and *reaches*, since those are the elements a reach can be connected to based on the datamodel (subclasses of *wastewater networkelement*). I am not aware of a spec that would request to change this functionality.

**Comment by lbartoletti** [comment]
Hi @m-kuhn 

If I understood correctly, we should not expect to have a snap as we are used to, but a pre-determined snap as you indicate.

My remark was that when we change the type of snapping in QGIS, we usually respect it, but if for the need of this tool (which I understand), we impose a way to snap then it can make sense. 

If that's what it is, we should just document it.

Thank you.

**Comment by m-kuhn** [comment]
On a technical level I don't have a strong opinion yet. I think it could make sense to use the standard configuration as well (e.g. to use construction layers or draw pipes parallel to a street layer ...) and either always add the topological layers or only add them when added to the config or a visibility based state, ... I'm open.

The main point here is, that we had to do a global offer for "appearance and Z of snapping" which to my understanding does not include functional changes to snapping layers, functional changes to visibility as well as changes to the mouse cursor. Those are good requirements but I think they should be split into a new issue.

**Comment by lbartoletti** [comment]
You're right, it's related, but it's not the demand.

**Comment by haubourg** [comment]
Agreed with @m-kuhn concerning the perimeter of that issue.

> The main point here is, that we had to do a global offer for "appearance and Z of snapping" which to my understanding does not include functional changes to snapping layers, functional changes to visibility as well as changes to the mouse cursor. Those are good requirements but I think they should be split into a new issue.

@ponceta just a ping to inform you about the perimeter of the snapping configuration in QGEP plugin.

**Comment by 3nids** [comment]
@lbartoletti thanks for the testing.

* snapping on Z has been fixed (it was working on point layers only). There was an issue in the SIP bindings in 2.18, so it will be usable coming from next release (2.18.21). If you compile 2.18 yourself, just discard the check in qgepmaptooladdfeature.py https://github.com/QGEP/qgepplugin/blob/da97a86efc01b3b9fc01d48d82239b9945d3bb4a/tools/qgepmaptooladdfeature.py#L313 A warning is displayed to the user saying snapping on Z cannot be achieved in given QGIS version
* snapping marker is now coherent with QGIS 2.18
* dotted line rendering has been fixed
* profiling and so are working again

will publish a release asap

**Comment by lbartoletti** [comment]
Hi @3nids 
Thank you for the corrections

Snapping indicator is ok for me.

Only a little doubt on my tests for Z, can you see me an example please?

@ponceta have you also tested with qgis-ltr nightly?

**Comment by 3nids** [comment]
@lbartoletti I tested again, and both altitude in reach points and in progression geometry of the reach is set.
Are you snapping onto lines or points?
Since you're showing CompoundCurve, I guess you're using the reach digitizing tool (and not wastewater structure, which was not part of this work).
I don't really understand what happens.
Can you maybe do a screencast or describe step by step how to reproduce?

**Comment by lbartoletti** [comment]
Demonstration made by Denis
https://youtu.be/u0NbpTH6Uho

**Comment by ponceta** [comment]
On QGIS 2.18.20-13 (qgis-ltr-dev), I get:

![image](https://user-images.githubusercontent.com/8614223/41655916-b1b7deca-748e-11e8-9642-f20338e118ed.png)

When snapping over ww_structures.

But snapping on 3D points seems to work 

![image](https://user-images.githubusercontent.com/8614223/41656509-7b8bf0e6-7490-11e8-98d7-8a44a7200b7c.png)

**Comment by haubourg** [comment]
@ponceta Yes that is a message added by @3nids because snapping bindings where broken in QGIS 2.18.20. You can test 2.18 dev version with OSGEO4W, it is built as a nighlty (just as master). It is call ltr-dev I think.

**Comment by 3nids** [comment]
yes, snapping on points is working fine!
If no objection, closing this issue.

**Comment by ponceta** [comment]
2.18.21 is out in 2 days according to :

Time until next pointrelease 2018-06-22 12:00:00 UTC 1d 22h 55m 

I close this and reopen if needed.

**Comment by haubourg** [comment]
I tested today with OSGEO4W,  qgis-ltr-dev bc6c940339 , qgep plugin v0.7.5 and face traceback exceptions:

```
2018-06-21T04:57:55	1	Traceback (most recent call last):
			  File "C:/Users/IEUser/.qgis2/python/plugins\qgepplugin\tools\qgepmaptools.py", line 136, in canvasReleaseEvent
			    self.leftClicked(event)
			  File "C:/Users/IEUser/.qgis2/python/plugins\qgepplugin\tools\qgepmaptools.py", line 449, in leftClicked
			    self.getTree(snapped_point.snappedAtGeometry)
			  File "C:/Users/IEUser/.qgis2/python/plugins\qgepplugin\tools\qgepmaptools.py", line 396, in getTree
			    nodes, edges = self.networkAnalyzer.getTree(point, upstream)
			  File "C:/Users/IEUser/.qgis2/python/plugins\qgepplugin\tools\qgepnetwork.py", line 364, in getTree
			    self.createGraph()
			  File "C:/Users/IEUser/.qgis2/python/plugins\qgepplugin\tools\qgepnetwork.py", line 229, in createGraph
			    self._addVertices()
			  File "C:/Users/IEUser/.qgis2/python/plugins\qgepplugin\tools\qgepnetwork.py", line 129, in _addVertices
			    self.graph.add_node(fid, dict(point=vertex, objType=obj_type, objId=obj_id))
			TypeError: add_node() takes exactly 2 arguments (3 given)
			
``` 

@3nids do I do something wrong? Should we reopen the issue?

**Comment by m-kuhn** [comment]
which version of networkx?

**Comment by haubourg** [comment]
2.0-1 installed today with osgeo4W setup

**Comment by ponceta** [comment]
QGIS 2.18.21 is out and it's not sufficient:

![image](https://user-images.githubusercontent.com/8614223/41836735-ea71fb8a-785b-11e8-89fb-eb7275584971.png)

Snapping on construction points (Points 3D) works fine.

Snapping on wastewater structures (Points 2D + Altitude attributaire) does not work properly since altitude is not saved in the reach geometry.

**Comment by haubourg** [comment]
@3nids Hi Denis, can you confirm that the z coordinate should be created on new reaches on the vertices that are snapped to another 3D reference feature ? 
@ponceta and @lbartoletti  couldn't have it work correctly. Thanks for your quick feeback.

**Comment by ponceta** [comment]
In march 2017 I suggested to go full 3D -> https://github.com/QGEP/datamodel/pull/34#issuecomment-290722994. Now could be the adequate time to fix this once and for all.

If wastewater nodes and covers go 3D (PointZ), then plugin is not an issue anymore.

And to handle attribute information up to date, we only have to add some triggers like QWAT's :

https://github.com/qwat/qwat-data-model/blob/7179cae7864773f28c61e060bf36295af0bc57ed/ordinary_data/valve/od_valve.sql#L182-L195

**Comment by haubourg** [comment]
@ponceta I agree that triggers should do the trick. However, we should really clarify what is done on client side and what is done on DB side. If we stay on foot on each, that will be a really messy situation. I'd just like that the current plugin logic works as is and discuss the database API as a whole thing.

**Comment by haubourg** [comment]
OK, we had a talk with @ponceta . The last remaining glitch is to handle altitude on the Wastewaterstructure point layer, which is a different topic than having the plugin able to snap existing Z features. 

So we add one argument here for https://github.com/QGEP/QGEP/issues/371  (ie don't use main cover for wastewaterstructure representation but use the node instead, and handle Z node)

to me, this issue can be closed.

**Comment by sjib** [comment]
VSA-DSS model is currently a 2.5 D model with a geometry2D coordinate and a attribute for the level (z-coordinate). If you switch it to a geometry3D coordinate - then a trigger would have to fill in the connected level attribute:

- So when you digitize a cover - then the z-coordinate would be in cover.level, not wastewater_node.bottom_level
- When you digitize a wastewater_node (x,y) then the corresponding z- attribute is wastewater_node.bottom_level. 
- When you digitize a reach_point, then the corresponding z-attribut is the reach_point.level

**Comment by haubourg** [comment]
thanks @sjib ! 
Are you aware of any other plan in the QGEP user group to go to a full 3D model?
