### ISSUE TITLE
using PUM with win7/10

### ISSUE THREAD

**Issue by kfischerar** [QGEP/QGEP#432]
i think it's a general question: how can i use a python-script written in a linux environment ?
may be i need a compiler to produce a EXE file ?

**Comment by sjib** [comment]
https://docs.python.org/3/using/windows.html

**Comment by m-kuhn** [comment]
I think in the long run we want a user interface for PUM.
For now, it needs to be managed by someone with the required experience on the console.

**Comment by olivierdalang** [comment]
pum is now working on windows (https://github.com/opengisch/pum/pull/74), but we still need to improve docs to explain how to use it, including from the OSGeo4W shell (which packages are required, how to get pg_dump and pg_restore executables, etc...)

**Comment by varrieta** [comment]
I'm trying to use PUM on windows but I run into an access issue (eventhough I ran the osgeoshell as administrator). See command line (dump function) and error message below: 

`pum -c ##\PUM\pum_config.yaml dump -p pg_qgep3 '##\PUM\backup.dump'`

```
 Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\Scripts\pum-script.py", line 11, in <module>
    load_entry_point('pum==0.9.10', 'console_scripts', 'pum')()
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\scripts\pum.py", line 594, in main
    pum.run_dump(args.pg_service, args.file, args.exclude_schema)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\scripts\pum.py", line 152, in run_dump
    dumper.pg_backup(pg_dump_exe=self.pg_dump_exe, exclude_schema=exclude_schema)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pum\core\dumper.py", line 40, in pg_backup
    output = subprocess.run(command, capture_output=True, text=True)
  File "C:\OSGEO4~1\apps\Python37\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\OSGEO4~1\apps\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\OSGEO4~1\apps\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Accès refusé
```
pum version: 0.9.10 / pirogue version: 1.1.0

Any ideas?

@3nids : same issue I had last year and I thought I would give it a second try since PUM was adapted to windows

**Comment by m-kuhn** [comment]
CC @olivierdalang

**Comment by olivierdalang** [comment]
@varrieta 
Hmm, not sure what it is, but if you're running the shell as admin, it's likely not a permission issue... Do you have lines that look like this in your pum_config.yml  : 
```
pg_dump_exe: C:\Program Files\PostgreSQL\9.3\bin\pg_dump.exe
pg_restore_exe: C:\Program Files\PostgreSQL\9.3\bin\pg_restore.exe
``` 
(the actual path may vary depending on which version of PostgresSQL/Pgadmin you've installed, also make sure pg_dump.exe and pg_restore.exe actually exist at these locations).

**Comment by varrieta** [comment]
I do and the .exe exists at this location

```
pg_dump_exe: '"C:\Program Files\PostgreSQL\10\bin\pg_dump.exe"'

pg_restore_exe: '"C:\Program Files\PostgreSQL\10\bin\pg_restore.exe"'
```

**Comment by varrieta** [comment]
I don't know if it helps but `pum check` does work

**Comment by olivierdalang** [comment]
Maybe it's the quotes in the config file ? Did you try removing the quotes (both `'` and `"`, they aren't needed in the yaml format, and may confuse pum when trying to run the pg_dump command).

And try to avoid spaces (if any) also in the `pum dump ...` command. You can just `cd` in the `##\PUM` directory and use relative paths so that you don't need to rename or move folders.

**Comment by olivierdalang** [comment]
@varrieta Did it work ?

**Comment by varrieta** [comment]
@olivierdalang sorry for the late answer. I just tried it now and.. it works 👍 it was the quotes..
Thanks a lot!

I'll run more test on today and let you know

**Comment by varrieta** [comment]
@olivierdalang I get this message running the upgrade cmd:
![image](https://user-images.githubusercontent.com/20111558/83853364-7bb78d00-a715-11ea-9111-6dfe305dfbbe.png)

Also, if I don't add the -t and -d infos, it doesn't work. Eventough it is already in the pum_config.yaml (here above).. 

```
pg_dump_exe: C:\Program Files\PostgreSQL\10\bin\pg_dump.exe
pg_restore_exe: C:\Program Files\PostgreSQL\10\bin\pg_restore.exe
delta_dir: delta
upgrades_table: qgep_sys.pum_info
backup_file: backup.dump
ignore_elements:
  - constraints
  - views
```

More infos: 
- test db: v1.3.1

**Comment by varrieta** [comment]
upgrade cmd works but I get this message after it applied the last delta.

`Applying post-all.py... No module named 'view'`

**Comment by olivierdalang** [comment]
@varrieta I think you have to be in the datamodel directory so that the view module gets picked up (meaning `cd C:\.....\datamodel` before running `pum upgrade (...)`).

There's definitely room for improvement in terms of user friendliness of the upgrade process :-)

**Comment by varrieta** [comment]
@olivierdalang Ok I'll try. But what does the view module?

**Comment by olivierdalang** [comment]
It (re)creates the views, which happens after all migrations have been made.

It is required as the views are rather complex, since they depend on potential customisations of the data model. They can't be easily expressed in a normal diff.

**Comment by sjib** [comment]
![grafik](https://user-images.githubusercontent.com/1265865/84120615-5dfc6780-aa36-11ea-928a-f02037aa66b7.png)

Screenshot for documentation
