### ISSUE TITLE
Error with the SQL-Button (refresh network topology)

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#444]
2018-08-21T08:15:51     CRITICAL    Warning : FEHLER: Berechtigung nur für Eigentümer der Relation vw_network_segment
             (42501) QPSQL: Es konnte keine Abfrage erzeugt werden
2018-08-21T08:15:51     WARNING    Python-Fehler : Ein Fehler trat bei der Ausführung von Python-Code auf: Mehr Details im Protokoll (Python-Fehler).

and this is the Python-Fehler:
2018-08-21T08:15:51     WARNING    Traceback (most recent call last):
              File "C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\qgepplugin\qgepplugin.py", line 314, in refreshNetworkTopologyActionClicked
              self.network_analyzer.refresh()
              File "C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\qgepplugin\tools\qgepnetwork.py", line 188, in refresh
              self.message_emitted.emit(self.tr("Warning"), str_result, QgsMessageBar.CRITICAL)
             AttributeError: type object 'QgsMessageBar' has no attribute 'CRITICAL'

**Comment by urskaufmann** [comment]
I get also with plugin version 1.1.3 an error (I can execute the refresh materialized view.sql in pgAdmin, but not with the SQL-Button):


2018-09-10T08:34:31     CRITICAL    Warning : FEHLER: Berechtigung nur für Eigentümer der Relation vw_network_segment
             (42501) QPSQL: Es konnte keine Abfrage erzeugt werden
2018-09-10T08:34:31     CRITICAL    Warning : FEHLER: Berechtigung nur für Eigentümer der Relation vw_network_node
             (42501) QPSQL: Es konnte keine Abfrage erzeugt werden
2018-09-10T08:34:31     WARNING    Python-Fehler : Ein Fehler trat bei der Ausführung von Python-Code auf: Mehr Details im Protokoll (Python-Fehler).

with python-error

2018-09-10T08:34:31     WARNING    Traceback (most recent call last):
              File "C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\qgepplugin\qgepplugin.py", line 314, in refreshNetworkTopologyActionClicked
              self.network_analyzer.refresh()
              File "C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\qgepplugin\tools\qgepnetwork.py", line 192, in refresh
              self.graph.clear()
             AttributeError: 'NoneType' object has no attribute 'clear'
