### ISSUE TITLE
SWMM Plugin: Error when creating Input with postgis qgep database on external server

### ISSUE THREAD

**Issue by MoritzBrennecke** [QGEP/QGEP#575]
qgep installed on external server. pg_service is working (acces to swmm-views given). When launching, the error message appears:

Démarrage de l'algorithme 'SWMM Create Input'…
Paramètres en entrée:
{ 'DATABASE' : 'pg_commune', 'INP_FILE' : 'TEMPORARY_OUTPUT', 'TEMPLATE_INP_FILE' : 'C:\\Users\\Moritz\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\Triform\\python\\plugins\\qgepplugin\\swmm\\default_qgep_swmm_parameters.inp' }

Traceback (most recent call last):
File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform/python/plugins\qgepplugin\processing_provider\swmm_create_input.py", line 89, in processAlgorithm
qs.write_input()
File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform/python/plugins\qgepplugin\processing_provider\QgepSwmm.py", line 184, in write_input
f.write(self.swmm_table('RAINGAGES'))
File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform/python/plugins\qgepplugin\processing_provider\QgepSwmm.py", line 91, in swmm_table
data, attributes = self.get_swmm_table(table_name)
File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform/python/plugins\qgepplugin\processing_provider\QgepSwmm.py", line 65, in get_swmm_table
con = psycopg2.connect(service=self.service)
File "C:\OSGEO4~1\apps\Python37\lib\site-packages\psycopg2\__init__.py", line 126, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "192.168.7.43 " to address: Unknown host

Service definition file:

[pg_commune]
host=192.168.7.43
port=5432
dbname=qgep_commune
user=TF_QGEP
password=XXX

**Comment by m-kuhn** [comment]
Can you check that the service definition file has unix line endings? (http://wiki.secondlife.com/wiki/How_to_avoid_DOS_line_endings_in_Windows_tools --> e.g. notepad++)

**Comment by MoritzBrennecke** [comment]
Yes, that worked, thank you. Maybe include a line in the documentation or in the error message?

**Comment by m-kuhn** [comment]
That's already in place https://qgep.github.io/docs/en/installation-guide/workstation.html

![image](https://user-images.githubusercontent.com/588407/84626514-80cec600-aee5-11ea-892f-fbbd7f454e5e.png)
