### ISSUE TITLE
Qgepswmm not found

### ISSUE THREAD

**Issue by YenniferC** [QGEP/QGEP#589]
Hello, 
I am trying to use the SWMM pluging, but in the processing options of the plugin I do not have the SWMM Create DB Tables, I only have create input, execute and extract results. So I went directly to create input and I got the following message first with the database by deafult that appears in the tool pg_qgep_demo_data, and then trying to go for pg_qgep.

QGIS version: 3.10.3-A Coruña
QGIS code revision: 0e1f846438
Qt version: 5.11.2
GDAL version: 3.0.4
GEOS version: 3.8.0-CAPI-1.13.1 
PROJ version: Rel. 6.3.1, February 10th, 2020
Processing algorithm…
Algorithm 'SWMM Create Input' starting…
Input parameters:
{ 'DATABASE' : 'pg_qgep_demo_data', 'INP_FILE' : 'TEMPORARY_OUTPUT', 'TEMPLATE_INP_FILE' : 'F:\\Aufträge\\JAM31558 Kingston\\Hydraulics\\04 WW_Baseline\\KSA_V19_Prposed-DS-2050_WetW\\default_qgep_swmm_parameters.inp' }

Traceback (most recent call last):
File "C:/Users/cufino/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\processing_provider\swmm_create_input.py", line 89, in processAlgorithm
qs.write_input()
File "C:/Users/cufino/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\processing_provider\QgepSwmm.py", line 184, in write_input
f.write(self.swmm_table('RAINGAGES'))
File "C:/Users/cufino/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\processing_provider\QgepSwmm.py", line 91, in swmm_table
data, attributes = self.get_swmm_table(table_name)
File "C:/Users/cufino/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\processing_provider\QgepSwmm.py", line 65, in get_swmm_table
con = psycopg2.connect(service=self.service)
File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\psycopg2\__init__.py", line 126, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: definition of service "pg_qgep_demo_data" not found

Execution failed after 0.30 seconds

Loading resulting layers
Algorithm 'SWMM Create Input' finished

QGIS version: 3.10.3-A Coruña
QGIS code revision: 0e1f846438
Qt version: 5.11.2
GDAL version: 3.0.4
GEOS version: 3.8.0-CAPI-1.13.1 
PROJ version: Rel. 6.3.1, February 10th, 2020
Processing algorithm…
Algorithm 'SWMM Create Input' starting…
Input parameters:
{ 'DATABASE' : 'pg_qgep', 'INP_FILE' : 'TEMPORARY_OUTPUT', 'TEMPLATE_INP_FILE' : 'F:\\Aufträge\\JAM31558 Kingston\\Hydraulics\\04 WW_Baseline\\KSA_V19_Prposed-DS-2050_WetW\\default_qgep_swmm_parameters.inp' }

Traceback (most recent call last):
File "C:/Users/cufino/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\processing_provider\swmm_create_input.py", line 89, in processAlgorithm
qs.write_input()
File "C:/Users/cufino/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\processing_provider\QgepSwmm.py", line 184, in write_input
f.write(self.swmm_table('RAINGAGES'))
File "C:/Users/cufino/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\processing_provider\QgepSwmm.py", line 91, in swmm_table
data, attributes = self.get_swmm_table(table_name)
File "C:/Users/cufino/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\processing_provider\QgepSwmm.py", line 65, in get_swmm_table
con = psycopg2.connect(service=self.service)
File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\psycopg2\__init__.py", line 126, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError

Execution failed after 0.08 seconds

Loading resulting layers
Algorithm 'SWMM Create Input' finished

When I run the code in the Python console I get this error:

PGSERVICE = 'pg_qgep'
DBMODEL = 'C:\\QGEP\\datamodel\\swmm_views'
qs = QgepSwmm(None, PGSERVICE, None, None, None, None, None, DBMODEL)
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
NameError: name 'QgepSwmm' is not defined

Any idea of what I am missing and how to fix it?

Thank you in advance.

**Comment by tproduit** [comment]
The documentation is not up to date. I need to fix it. 

You are right to start directly with `SWMM Create Input`. The problem seems to be that in the field Database, you need to put the name of the service which define the connection to your database. If you don't know it, you should find the name of the service in the definition of the layers (right clic on a qgep layer in QGIS).
