### ISSUE TITLE
snap to vertices of a point layer

### ISSUE THREAD

**Issue by tproduit** [QGEP/QGEP#596]
Step to reproduce the error:
* Add a point layer to a QGEP project
* Enable snap to all layers
* Start Data Entry > Reach
* Try to snap to the point layer:

![image](https://user-images.githubusercontent.com/8256037/91036228-4715ec00-e607-11ea-9e54-b2d0177eaf38.png)

* The snap icon is no visible (but the mouse is attracted by the point)
* The snap generate an error

```
2020-08-24T12:42:59     WARNING    Traceback (most recent call last):

              File "C:/Users/tproduit/AppData/Roaming/QGIS/QGIS3\profiles\qgep_prod/python/plugins\qgepplugin\tools\qgepmaptooladdfeature.py", line 135, in cadCanvasReleaseEvent
              self.left_clicked(event)

              File "C:/Users/tproduit/AppData/Roaming/QGIS/QGIS3\profiles\qgep_prod/python/plugins\qgepplugin\tools\qgepmaptooladdfeature.py", line 220, in left_clicked
              point3d, match = self.snap(event)

              File "C:/Users/tproduit/AppData/Roaming/QGIS/QGIS3\profiles\qgep_prod/python/plugins\qgepplugin\tools\qgepmaptooladdfeature.py", line 281, in snap
              point = QgsPoint(f.geometry().constGet())

             TypeError: Invalid type in constructor arguments.
```

**Comment by tproduit** [comment]
Thanks guys, it works like a charm!
