### ISSUE TITLE
Error with datamodel tool

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#664]
I have created a new database in pgAdmin. If I create then a new PG Config setup with the datamodel tool, I get an error 
.

![Fehler1 2021-07-07 142939](https://user-images.githubusercontent.com/1257403/124764384-2dd31100-df35-11eb-8119-f9563bb250e0.png)

If I choose then this new PG Config setup, I get also an error .

![Fehler2 2021-07-07 142649](https://user-images.githubusercontent.com/1257403/124764429-39bed300-df35-11eb-8570-500295eeb91e.png)

If I choose an other PG Config setup with an Database that already has a QGEP-schema, there is now error.

Well – on the 23.6.2021 I could create the QGEP-schema in a new database, now I get this error.

I have an idea what can be the reason (because I had an error this week with my import/export-bat-files, that worked before):
We work know since several weeks with QGIS 3.16, but it seems, that the version 3.10 was deleted last week from the virtual-pc we work with (after both versions where installed parallel during several weeks).
So what can be done?

**Comment by sjib** [comment]
a) Do you have an Umlaut ä, ö, ü etc. somewhere - that is usually what conflicts with UTF-8. 
b) pg_conf needs to be saved with special encoding https://qgep.github.io/docs/installation-guide/workstation.html#windows-pg-service 
On Windows, you need to save pg_service.conf in Unix format in order to work. One way to do it is to open it with Notepad++ and Edit –> EOL Conversion –> UNIX Format –> File save .

**Comment by urskaufmann** [comment]
There are no Umlaute, also no capital letters.
There is only the datamodel tool writing into pg_service.conf-file (EOL Format is Unix LF).

**Comment by sjib** [comment]
@olivierdalang Any idea what could be the problem?

**Comment by olivierdalang** [comment]
Not exactly sure why this is happening, but I've just pushed a commit (https://github.com/QGEP/qgepplugin/commit/a063ee590b7fa9535b83487e031058149a31c073) with a possible fix. Can you try with master, and reopen this issue if it is not fixed ?

**Comment by olivierdalang** [comment]
@urskaufmann Tried another fix, can you try again ?

**Comment by urskaufmann** [comment]
2021-07-08T12:04:57     WARNING    Traceback (most recent call last):
              File "C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\Holinger/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 587, in select_pgconfig
              self.check_version()
              File "C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\Holinger/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 96, in wrapper
              return func(*args, **kwargs)
              File "C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\Holinger/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 639, in check_version
              current_version = self._get_current_version()
              File "C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\Holinger/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 366, in _get_current_version
              error_message="Could not get current version, are you sure the database is accessible ?",
              File "C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\Holinger/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 297, in _run_cmd
              encoding="cp437" if os.name == "nt" else "utf-8",
              File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\subprocess.py", line 455, in run
              stdout, stderr = process.communicate(input, timeout=timeout)
              File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\subprocess.py", line 920, in communicate
              stdout, stderr = self._communicate(input, endtime, timeout)
              File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\subprocess.py", line 1265, in _communicate
              stdout = stdout[0]
             IndexError: list index out of range

**Comment by olivierdalang** [comment]
Can you type this in your command prompt : `chcp` (this will show encoding used by your system)

**Comment by urskaufmann** [comment]
Aktive Codepage: 437.

**Comment by olivierdalang** [comment]
Argh that's tricky :-/ I added yet another tentative fix, can you test again ? (sorry for that !)

**Comment by m-kuhn** [comment]
@olivierdalang maybe this approach here works better?
 https://github.com/opengisch/QgisModelBaker/blob/master/QgisModelBaker/libili2db/iliexecutable.py#L129-L161

**Comment by urskaufmann** [comment]
Better and good. I get now this message

2021-07-08T13:04:52     WARNING    Running command : python -m pum info -p pg_w_zh_rueti_gep -t qgep_sys.pum_info -d C:\Users\KAU\AppData\Local\Temp\QGEP\datamodel-init\datamodel-1.5.5\delta
2021-07-08T13:04:55     WARNING    delta files in dir: C:\Users\KAU\AppData\Local\Temp\QGEP\datamodel-init\datamodel-1.5.5\delta 
             FEHLER: Relation �qgep_sys.pum_info� existiert nicht 
             LINE 2: SELECT id FROM qgep_sys.pum_info 

but the dialog shows the correct info, that qgep is not initialized. Then I can install the schemas and this did work..!!

**Comment by olivierdalang** [comment]
Great, closing this then. Thanks for the report
