### ISSUE TITLE
Error with datamodel tool - Load QGIS Project template

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#665]
When loading the QGIS Project template, I get this error (see below). Not urgent, I know how to copy manually.

2021-07-09T09:19:54     WARNING    Traceback (most recent call last):
              File "C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\Holinger/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 96, in wrapper
              return func(*args, **kwargs)
              File "C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\Holinger/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 876, in load_project
              qgep_path = self._download(url, "qgep.zip")
              File "C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\Holinger/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 326, in _download
              raise QGEPDatamodelError(error_message)
             qgepplugin.gui.qgepdatamodeldialog.QGEPDatamodelError: Error transferring https://github.com/QGEP/QGEP/releases/download/v9.0/qgep.zip - server replied: Not Found
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\Holinger/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 98, in wrapper
              args[0]._show_error(str(e))
              File "C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\Holinger/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 249, in _show_error
              self._done_progress()
              File "C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\Holinger/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 243, in _done_progress
              self.progress_dialog.close()
             AttributeError: 'NoneType' object has no attribute 'close'

**Comment by ponceta** [comment]
Duplicate with :

https://github.com/QGEP/QGEP/issues/676
