### ISSUE TITLE
Pythonerror on starting QGEP

### ISSUE THREAD

**Issue by tomep** [QGEP/QGEP#681]
**Describe the bug**
2021-08-23T10:39:04     CRITICAL    Traceback (most recent call last):
              File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/tomholeci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\__init__.py", line 27, in classFactory
              from .qgepplugin import QgepPlugin
              File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/tomholeci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepplugin.py", line 40, in 
              from .gui.qgepplotsvgwidget import QgepPlotSVGWidget
              File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/tomholeci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\gui\qgepplotsvgwidget.py", line 34, in 
              from ..tools.qgepnetwork import QgepGraphManager
              File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/tomholeci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepnetwork.py", line 39, in 
              import networkx as nx
              File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'networkx'

**To Reproduce**
Exact steps to reproduce the behavior:

**Expected behavior**

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version 1.5.5-2
 - QGEP datamodel version 1.5.4
 - QGEP project file version 20210528
 - QGIS Version 3.16.8
 - OS Win10

**Additional context**

**Comment by m-kuhn** [comment]
> ModuleNotFoundError: No module named 'networkx'

You need to install networkx (see https://qgep.github.io/docs/en/installation-guide/workstation.html#install-qgep-plugin)

**Comment by sjib** [comment]
Could we adapt the plugin so that networkx is installed automatically in a future release? I think dependencies were not yet so easy when you developed the plugin @m-kuhn - how is it today? If yes, could you open a new task to do so - if no then please close.

**Comment by m-kuhn** [comment]
The situation is still similar as years ago. @olivierdalang and I worked on a QEP for dependency management but the topic is complex and was discussed controversially and didn't make it through to funding yet.

We could possibly bundle it as wheel with the plugin, this is likely a working solution to make setup easier.

**Comment by sjib** [comment]
Thanks for the update
