### ISSUE TITLE
Error SWMM Create Input - Column has Z dimension but geometry does not

### ISSUE THREAD

**Issue by TriformMoritz** [QGEP/QGEP#690]
Error when trying to create an input (modell 1.5.5) :

Chargement des couches de résultat
Algorithme 'SWMM Create Input' terminé
Version de QGIS : 3.16.4-Hannover
Révision du code : 654e76b3cb
Version de Qt : 5.11.2
Version de GDAL : 3.1.4
Version de GEOS : 3.8.1-CAPI-1.13.3
Version de Proj : Rel. 6.3.2, May 1st, 2020
Traitement de l'algorithme…
Démarrage de l'algorithme 'SWMM Create Input'…
Paramètres en entrée:
{ 'DATABASE' : 'pg_monthey154_restore', 'INP_FILE' : 'TEMPORARY_OUTPUT', 'STATE' : 0, 'TEMPLATE_INP_FILE' : 'C:\\Users\\Moritz\\Documents\\NEW_INPUT.inp' }

Traceback (most recent call last):
File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins\qgepplugin\processing_provider\swmm_create_input.py", line 128, in processAlgorithm
qs.write_input()
File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins\qgepplugin\processing_provider\QgepSwmm.py", line 249, in write_input
f.write(self.swmm_table("CONDUITS", state, ws=True))
File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins\qgepplugin\processing_provider\QgepSwmm.py", line 122, in swmm_table
data, attributes = self.get_swmm_table(table_name, state, ws)
File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins\qgepplugin\processing_provider\QgepSwmm.py", line 93, in get_swmm_table
cur.execute(sql)
psycopg2.errors.InvalidParameterValue: ERREUR: Column has Z dimension but geometry does not

L’exécution a échoué après 4.63 secondes

Chargement des couches de résultat
Algorithme 'SWMM Create Input' terminé

Here are my versions (database 1.5.5 -> upgrade from version 1.5.4 via Datamodel tool, QGEP 1.5.5)

![image](https://user-images.githubusercontent.com/33837122/131876260-804fddd5-5e00-43eb-9f29-4a2cb07c50ce.png)

Worked before, not working anymore.

**Comment by TriformMoritz** [comment]
Error was one node with no status -> Should be nice if the error message would be more accurate!

**Comment by sjib** [comment]
@TriformMoritz Which view should check if status is set?

The following views now have all an ELSE statement for current / planned:
swmm_views/02_vw_swmm_junctions.sql
swmm_views/05_vw_swmm_dividers.sql
swmm_views/13_vw_swmm_storages.sql

May be we can add a hint to the documentation that there can be problems in simulation if not all elements are exported because the lack a status.
Or add a separate view as pre-process that checks on wastewater_structures where status isNull ?

![wastewater_structures_without_status](https://user-images.githubusercontent.com/1265865/152119561-097b2a31-202c-4004-90d8-fa8003f53eff.jpg)

What do you think?

**Comment by TriformMoritz** [comment]
It would be nice to have an error message like this:
- The following elements do not have the status set : Node obj_id xxxx, ....
- Please set a status in order to export to SWMM.

Error message: psycopg2.errors.InvalidParameterValue: ERREUR: Column has Z dimension but geometry does not is not comprehensive.

**Comment by sjib** [comment]
Siehe auch https://github.com/QGEP/QGEP/issues/613

**Comment by tproduit** [comment]
In line https://github.com/QGEP/datamodel/blob/518a7b21c0c92c12311588c9c7ce028124a430ae/swmm_views/04_vw_swmm_conduits.sql#L26

`ST_CurveToLine(progression_geometry)::geometry(LineStringZ, %(SRID)s)  as geom,`

Must be replaced with

`ST_CurveToLine(st_force3d(progression_geometry))::geometry(LineStringZ, %(SRID)s)  as geom,`

It is quite unlikely that this error is related to the status of a node.
