### ISSUE TITLE
Length profile error with plugin 1.6.1

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#816]
**Describe the bug**
Python-Error when trying to make a lengthprofil. After that, the cursor turns on and on...
_2023-04-25T08:33:04     WARNING    Traceback (most recent call last):
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptools.py", line 148, in canvasReleaseEvent
              self.leftClicked(event)
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptools.py", line 482, in leftClicked
              pf = self.findPath(self.selectedPathPoints[-1][0], match.featureId())
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptools.py", line 318, in findPath
              self.appendProfile(vertices, edges)
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptools.py", line 417, in appendProfile
              elem = QgepProfileSpecialStructureElement(
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepprofile.py", line 318, in __init__
              QgepProfileEdgeElement.__init__(
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepprofile.py", line 92, in __init__
              self.addSegment(
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepprofile.py", line 403, in addSegment
              self.detailGeometry = node_cache.attrAsGeometry(
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepnetwork.py", line 447, in attrAsGeometry
              m = re.search("(.*;)?(.*)", ewktstring)
              File "C:\PROGRA~1\QGIS3\apps\Python39\lib\re.py", line 201, in search
              return _compile(pattern, flags).search(string)
             TypeError: expected string or bytes-like object_

**To Reproduce**
Exact steps to reproduce the behavior:
1. Click on QGEP Profile button
2. Click on start node, there is the orange line, click on end node.
3. Python-Fehler: Ein Fehler trat bei der Ausführung von Python-Code auf: Mehr Details im Protokoll (Python-Fehler).

**Expected behavior**
Profile

**Desktop (please complete the following information):**
 - QGEP plugin version 1.6.1
 - QGEP datamodel version 1.5.5, 1.5.6, 1.6.0
 - QGEP project file version
 - QGIS Version 3.28.5
 - OS Win 10

**Hint**
Network following works

**Comment by sjib** [comment]
Can confirm problem

Problem happens in https://github.com/QGEP/qgepplugin/blob/14639f5e71e09d26341081530f5b8faeadfd4cfd/qgepplugin/tools/qgepnetwork.py#LL441C4-L448C47

def attrAsGeometry(self, feat, attr):
        """
        Get an attribute as geometry
        """
        ewktstring = self.attrAsUnicode(feat, attr)
        **# Strip SRID=21781; token, TODO: Fix this upstream**
        m = re.search("(.*;)?(.*)", ewktstring)
        return QgsGeometry.fromWkt(m.group(2))

May be this workaround is fixed now upstreams and is not needed anymore

**Comment by sjib** [comment]
https://qgis.org/pyqgis/3.0/core/Geometry/QgsGeometry.html - maybe something has changed there.

**Comment by sjib** [comment]
Feedback von @cymed: Ich hatte den Fehler soeben auch, allerdings nur, wenn ich keinen rp_from_level oder rp_to_level hatte. Habe danach ein Experiment gemacht. Anscheinend funktioniert ST_SetPoint in der Test-DB nicht mit NaN-Werten in den zu setzenden Koordinaten (Postgis 3.3)…

**Comment by sjib** [comment]
![20230621_network_following_progression_geometry_error](https://github.com/QGEP/QGEP/assets/1265865/2399f7f5-075c-4e68-a0a4-d64ff61bf514)

**Comment by urskaufmann** [comment]
I get the error also if reachpoint_level and wastewater-node_bottomlevel is set...

**Comment by cymed** [comment]
> Feedback von @cymed: Ich hatte den Fehler soeben auch, allerdings nur, wenn ich keinen rp_from_level oder rp_to_level hatte. Habe danach ein Experiment gemacht. Anscheinend funktioniert ST_SetPoint in der Test-DB nicht mit NaN-Werten in den zu setzenden Koordinaten (Postgis 3.3)…

This issue is linked to problems in the wizard, separate issue tbd

**Comment by urskaufmann** [comment]
I created a Qfield-project from my QGEP-project. No special configurations.
I just open this *_qfield.qgs with QGIS.
And it's possible to use the network-following, and even the profile tool works as it worked in earlier days.

If I use the profile tool in the original QGEP-project, I get the error, it's not possible. Same QGIS, same plugin!

Well, its not a real workaround for the profile-tool, but astonishing anyway. Did somebody know this?
