### ISSUE TITLE
INTERLIS export fails using latest plugin

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#845]
**Describe the bug**

**To Reproduce**
Use the latest version of the master branch of the plugin and the latest demo dataset
1. Go to Interlis Export
2. Click on export

**Expected behavior**
The INTERLIS file is correctly exported 

**Screenshots / data**
```
qgepplugin.qgepqwat2ili.qgepqwat2ili.utils.various.CmdException: Command errored ! See logs for more info. 
Traceback (most recent call last):
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\utils\various.py", line 50, in exec_
    proc = subprocess.run(
  File "C:\OSGeo4W\apps\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '"C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe" -jar "C:\Users\pulpoar\AppData\Roaming\QGIS\QGIS3\profiles\pulpoar\python\plugins\QgisModelBaker\libili2db\bin\ili2pg-4.6.1\ili2pg-4.6.1.jar" --schemaimport --dbhost "myhost.pully.ch" --dbport "5432" --dbusr "myadminpostgres" --dbpwd "mypassword" --dbdatabase "qgep_demo" --dbschema pg2ili_sia405abwasser --setupPgExt --createGeomIdx --createFk --createFkIdx --createTidCol --importTid --noSmartMapping --defaultSrsCode 2056 --log "C:/temp/INTERLIS/export/qgep-demo-export.xtf.240305102910.ili2pg-schemaimport.log" --nameLang de C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\ili\SIA405_Abwasser_2015_2_d-20180417.ili' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 501, in action_do_export
    create_ili_schema(
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\utils\ili2db.py", line 159, in create_ili_schema
    exec_(
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\utils\various.py", line 60, in exec_
    raise CmdException(f"Command errored ! See logs for more info.")
qgepplugin.qgepqwat2ili.qgepqwat2ili.utils.various.CmdException: Command errored ! See logs for more info.
```

![image](https://github.com/QGEP/QGEP/assets/8614223/70b6ad74-b68e-4b84-b4b1-79f214cd1435)

**Desktop (please complete the following information):**
 - QGEP plugin version master
 - QGEP datamodel version 1.6.0
 - QGEP project file version master
 - QGIS Version 3.34.4 LTR
 - OS Win 10 x64

**Additional context**

**Comment by ponceta** [comment]
Is it possible that ili2db can't access to postgres in these versions  and would need an upgrade?

**Comment by sjib** [comment]
@ponceta I think you have to install an older version of ModelBaker: Unmet dependencies with ModelBaker > 6.4.0 https://github.com/QGEP/qgepqwat2ili/issues/65

**Comment by sjib** [comment]
@domi4484 Or is it ili2db an Postgres 14.5?

**Comment by domi4484** [comment]
@ponceta can you post the ili logfile? It is saved here: `C:/temp/INTERLIS/export/qgep-demo-export.xtf.240305102910.ili2pg-schemaimport.log`

**Comment by ponceta** [comment]
```
Info: ili2pg-4.6.1-63db90def1260a503f0f2d4cb846686cd4851184
Info: ili2c-5.2.3-3ec7a10e9bacc87e149a14a7f11a6035e0481c69
Info: iox-ili-1.21.8-a6aee68136447c0616995e56888fa9c7ef362a77
Info: java.version 1.8.0_371
Info: user.name <pulpoar>
Info: maxMemory 7393280 KB
Info: currentTime 2024-03-05 10:29:12
Info: dbschema <pg2ili_sia405abwasser>
Info: dburl <jdbc:postgresql://postgis2.pully.ch:5432/qgep_demo>
Info: dbusr <postgres>
Error: org.postgresql.util.PSQLException: SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions)
Error:   SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions)
```

**Comment by ponceta** [comment]
It is indeed a scram issue linked to ili2pg and postgres 14

**Comment by sjib** [comment]
@ponceta Status of SCRAM support and possible work around with MD5 and/or status of ili2pg you can find here: https://github.com/claeis/ili2db/issues/448

**Comment by sjib** [comment]
Trying to change version of binaries: ili2pg and ilivalidator see https://github.com/QGEP/qgepqwat2ili/pull/138

Creates new issue with `column_T_basket` missing: https://github.com/QGEP/qgepqwat2ili/pull/138#issuecomment-2144405170
