### ISSUE TITLE
QGEP 1.62, Export of selection, wastewater_networkelement missing

### ISSUE THREAD

**Issue by urskaufmann** [qgep/QGEP#855]
**Describe the bug**
I exported to DSS, no selection, no labels: it works, no errors, validation ok.

I export now from the same database, same project to SIA405, with a selection of reaches and structures, with labels and I get the error below.

Seems, that the selection has a special case, where a not selected wastewater_networkelement is connected with fk to the reachpoint...
(example: a selected reach has a fk to another (not selected) reach, which has relations to nodes, that are also not selected...)

Ein Fehler trat bei der Ausführung von Python-Code auf: 

sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "haltungspunkt" violates foreign key constraint "haltungspunkt_abwassernetzelementref_fkey" DETAIL:  Key (abwassernetzelementref)=(6852) is not present in table "abwassernetzelement". (Background on this error at: http://sqlalche.me/e/13/gkpj) 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
    dbapi_connection.commit()
psycopg2.errors.ForeignKeyViolation: insert or update on table "haltungspunkt" violates foreign key constraint "haltungspunkt_abwassernetzelementref_fkey"
DETAIL:  Key (abwassernetzelementref)=(6852) is not present in table "abwassernetzelement".

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 608, in action_do_export
    qgepsia405_export(selection=export_dialog.selected_ids, labels_file=labels_file_path, orientation=eorientation)
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepsia405\export.py", line 1123, in qgep_export
    abwasser_session.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1046, in commit
    self.transaction.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 508, in commit
    t[1].commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1762, in commit
    self._do_commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1793, in _do_commit
    self.connection._commit_impl()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 773, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "haltungspunkt" violates foreign key constraint "haltungspunkt_abwassernetzelementref_fkey"
DETAIL:  Key (abwassernetzelementref)=(6852) is not present in table "abwassernetzelement".

(Background on this error at: http://sqlalche.me/e/13/gkpj)

Python-Version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS-Version: 3.34.4-Prizren Prizren, decd43dc 

Python-Pfad:
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3\apps\grass\grass83\etc\python
C:\Program Files\QGIS3\bin
C:\Program Files\QGIS3\bin\python39.zip
C:\PROGRA~1\QGIS3\apps\Python39\DLLs
C:\PROGRA~1\QGIS3\apps\Python39\lib
C:\PROGRA~1\QGIS3\apps\Python39
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python
P:/Thun/Gemeinden/110-119 Thun/O1010 Thun, Nachführung Werkplan Abwasser/qgep
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..

**Desktop (please complete the following information):**
 - QGEP plugin version 1.62
 - QGEP datamodel version 1.61
 - QGEP project file version -
 - QGIS Version 3.34.4
 - OS Win10

**Comment by ponceta** [comment]
Define a concept for the selection export to export all mandatory related classes to make the export successful / valid

**Comment by sjib** [comment]
see also https://github.com/QGEP/QGEP/issues/856

**Comment by sjib** [comment]
@urskaufmann 
> example: a selected reach has a fk to another (not selected) reach, which has relations to nodes, that are also not selected...
This happens quite easily in a reach - reach connection when the downstream reach is not also selected.

Seems to me quite difficult to define a filter join where this downstream reach is also automatically also selected.

Maybe we would need to add a join here that includes also all reaches and all wastewater_nodes that are link through fk_wastewater_network_element

```
    logger.info("Exporting QGEP.reach -> ABWASSER.haltung, ABWASSER.metaattribute")
    query = qgep_session.query(QGEP.reach)
    if filtered:
        query = query.filter(QGEP.wastewater_networkelement.obj_id.in_(subset_ids))
```

A little bit similar to Haltungspuntk - see this: https://github.com/QGEP/QGEP/issues/856#issuecomment-2110375326
