### ISSUE TITLE
Error during QGEP datamodel initialization: `FileNotFoundError: [Errno 2] No such file or directory: 'view/drop_views.sql'`

### ISSUE THREAD

**Issue by nicolas-sitylb** [qgep/QGEP#860]
**Describe the bug**
I met some errors while trying to install QGEP on Debian 12:
```sh
root@localhost:/data/datamodel/scripts# ./db_setup.sh > /data/qgep_build_output.txt
psql:/data/datamodel/01_audit.sql:20: NOTICE:  table "logged_actions" does not exist, skipping
psql:/data/datamodel/09_qgep_dictionaries.sql:5: NOTICE:  view "dictionary_value_list" does not exist, skipping
psql:/data/datamodel/09_qgep_dictionaries.sql:140: NOTICE:  type "qgep_od.plantype" does not exist, skipping
Traceback (most recent call last):
  File "/data/datamodel/scripts/../view/create_views.py", line 139, in <module>
    create_views(args.srid, args.pg_service,
  File "/data/datamodel/scripts/../view/create_views.py", line 47, in create_views
    drop_views(pg_service)
  File "/data/datamodel/scripts/../view/create_views.py", line 25, in drop_views
    run_sql('view/drop_views.sql', pg_service)
  File "/data/datamodel/scripts/../view/create_views.py", line 16, in run_sql
    sql = open(file_path).read()
FileNotFoundError: [Errno 2] No such file or directory: 'view/drop_views.sql'
```

Incriminated line: https://github.com/QGEP/datamodel/blob/aa5eac6a46b59a671a79f923599c7aef72bb0028/view/create_views.py#L25

**To Reproduce**
See here above, the errors were printed during the execution of the `db_setup.sh` script.

**Expected behavior**
No error should be printed during a fresh first time installation.

**Screenshots / data**
N/A

**Desktop (please complete the following information):**
 - QGEP plugin version: N/A
 - QGEP datamodel version: the datamodel code was cloned from github [`master` branch](https://github.com/QGEP/datamodel) as described [here](https://qgep.github.io/docs/en/installation-guide/database-initialization.html#generate-the-data-model-under-linux)
 - QGEP project file version: N/A
 - QGIS Version: N/A
 - OS: Debian 12

**Additional context**
PG: 13.6    
PostGIS: 3.2    
Python: 3.9.10    
pum: 0.10.1    
pirogue: 2.2.0

**Comment by ponceta** [comment]
Hello @nicolas-sitylb,
I've so many questions for you :
Why starting a qgep right now when TEKSI wastewater is almost out?
https://github.com/teksi/wastewater/releases/tag/2024.0.0
Why PG 13/3.2?
Please give me a call and we can go through it.
Maybe try to run it on folder lower :
`./scripts/setup.sh -p pg_qgep -s 2056`

**Comment by sjib** [comment]
@nicolas-sitylb no response from your side, please re-open if necessary

**Comment by nicolas-sitylb** [comment]
Hello @ponceta 

I've tried with Python 3.10.15 (Debian 12) on a PG 15 / PostGIS 3.4 cluster but the **same** error occurs.

I also tried your command from a folder upper in the hierarchy, which seems to solve the initial issue*, but I'm now facing the following error (when manually specifying the SRID using the `-s` flag or not) :

```sql
root@localhost:/data/datamodel# ./scripts/db_setup.sh -p qgep -s 2056
-s was triggered, SRID: 2056
CREATE EXTENSION
CREATE EXTENSION
CREATE SCHEMA
CREATE SCHEMA
CREATE SCHEMA
CREATE SCHEMA
CREATE SCHEMA
BEGIN
psql:/data/datamodel/01_audit.sql:20: NOTICE:  la table « logged_actions » n'existe pas, poursuite du traitement
DROP TABLE
CREATE TABLE
REVOKE
COMMENT
COMMENT
(...)
COMMENT
CREATE FUNCTION
CREATE TABLE
*** Failing:

CREATE OR REPLACE VIEW qgep_od.vw_qgep_overflow AS
  SELECT
    CASE
      WHEN leapingweir.obj_id IS NOT NULL THEN 'leapingweir'::qgep_od.overflow_type
      WHEN prank_weir.obj_id IS NOT NULL THEN 'prank_weir'::qgep_od.overflow_type
      WHEN pump.obj_id IS NOT NULL THEN 'pump'::qgep_od.overflow_type
      ELSE 'overflow'::qgep_od.overflow_type
    END AS overflow_type
    , overflow.obj_id
    , overflow.actuation
    , overflow.adjustability
    , overflow.brand
    , overflow.control
    , overflow.discharge_point
    , overflow.fk_control_center
    , overflow.fk_dataowner
    , overflow.fk_overflow_char
    , overflow.fk_overflow_to
    , overflow.fk_provider
    , overflow.fk_wastewater_node
    , overflow.function
    , overflow.gross_costs
    , overflow.identifier
    , overflow.last_modification
    , overflow.qon_dim
    , overflow.remark
    , overflow.signal_transmission
    , overflow.subsidies
    -- , leapingweir.obj_id
    , leapingweir.length
    , leapingweir.opening_shape
    , leapingweir.width
    -- , prank_weir.obj_id
    , prank_weir.hydraulic_overflow_length
    , prank_weir.level_max
    , prank_weir.level_min
    , prank_weir.weir_edge
    , prank_weir.weir_kind
    -- , pump.obj_id
    , pump.construction_type
    , pump.operating_point
    , pump.placement_of_actuation
    , pump.placement_of_pump
    , pump.pump_flow_max_single
    , pump.pump_flow_min_single
    , pump.start_level
    , pump.stop_level
    , pump.usage_current,
    n1.situation_geometry::geometry('PointZ',%(SRID)s) AS geometry
  FROM qgep_od.overflow overflow
    LEFT JOIN qgep_od.leapingweir leapingweir ON leapingweir.obj_id = overflow.obj_id
    LEFT JOIN qgep_od.prank_weir prank_weir ON prank_weir.obj_id = overflow.obj_id
    LEFT JOIN qgep_od.pump pump ON pump.obj_id = overflow.obj_id
    LEFT JOIN qgep_od.wastewater_node n1 ON overflow.fk_wastewater_node::text = n1.obj_id::text
;

***
Traceback (most recent call last):
  File "/data/datamodel/scripts/../view/create_views.py", line 139, in <module>
    create_views(args.srid, args.pg_service,
  File "/data/datamodel/scripts/../view/create_views.py", line 86, in create_views
    MultipleInheritance(safe_load(open("view/vw_oo_overflow.yaml")), create_joins=True, variables=variables, pg_service=pg_service, drop=True).create()
  File "/usr/local/lib/python3.10/site-packages/pirogue/multiple_inheritance.py", line 214, in create
    raise e
  File "/usr/local/lib/python3.10/site-packages/pirogue/multiple_inheritance.py", line 200, in create
    self.cursor.execute(psycopg.sql.SQL(_sql).format(**self.variables))
psycopg2.errors.SyntaxError: ERREUR:  erreur de syntaxe sur ou près de « % »
LINE 50:     n1.situation_geometry::geometry('PointZ',%(SRID)s) AS ge...
                                                      ^
```
The same error occurs with `psycopg` >= 3.

\* Personally, I'd be happy if the database initialization script could be run without error from any disk location.

@sjib : I can unfortunately not reopen a closed issue here as I'm not part of the current repository management team.

**Comment by ponceta** [comment]
@nicolas-sitylb https://github.com/teksi/wastewater/releases/tag/2024.0.5 is out, I would suggest we try to fix that there because we won't have much time for bugfixing QGEP next year since it will be archived end of 2025.

**Comment by sjib** [comment]
Seems to be a problem setting the SRID variable
