### ISSUE TITLE
Error on datamodel tool unicode character

### ISSUE THREAD

**Issue by ponceta** [qgep/QGEP#865]
**Describe the bug**
If the default pg_service points to a wrong destination, an error can occur.

**To Reproduce**
Exact steps to reproduce the behavior:

**Expected behavior**

**Screenshots / data**
Une erreur est survenue lors de l'exécution du code Python : 
```

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 122: invalid continuation byte 
Traceback (most recent call last):
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 678, in check_version
    current_version = self._get_current_version()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 390, in _get_current_version
    pum_info = self._run_cmd(
               ^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 339, in _run_cmd
    raise QGEPDatamodelError(message)
qgepplugin.gui.qgepdatamodeldialog.QGEPDatamodelError: Could not get current version, are you sure the database is accessible ?
Command :
python3 -m pum info -p pg_port -t qgep_sys.pum_info -d C:\Users\pulpoar\AppData\Local\Temp\QGEP\datamodel-init\datamodel-1.6.2\delta

Output :
'utf-8' codec can't decode byte 0xe9 in position 122: invalid continuation byte


Error :
None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 114, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 482, in switch_datamodel
    self.check_version()
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 114, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 686, in check_version
    self._run_sql(
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 295, in _run_sql
    conn = psycopg2.connect(connection_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pulpoar\AppData\Roaming\Python\Python312\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 122: invalid continuation byte

```
**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version
 - OS

**Additional context**

**Comment by sjib** [comment]
see also https://github.com/QGEP/QGEP/issues/879
