### ISSUE TITLE
Import failure plugin qgep_sys.drop_symbology

### ISSUE THREAD

**Issue by ponceta** [qgep/QGEP#867]
**Describe the bug**
Import failure plugin qgep_sys.drop_symbology

```
Une erreur est survenue lors de l'exécution du code Python : 

sqlalchemy.exc.ArgumentError: Textual SQL expression 'SELECT qgep_sys.drop_symb...' should be explicitly declared as text('SELECT qgep_sys.drop_symb...') 
Traceback (most recent call last):
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepplugin.py", line 539, in actionImportClicked
    action_import(self)
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 348, in action_import
    qgepdss_import(
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepdss\import_.py", line 33, in qgep_import
    pre_session.execute("SELECT qgep_sys.drop_symbology_triggers();")
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2089, in _execute_internal
    statement = coercions.expect(roles.StatementRole, statement)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\sql\coercions.py", line 396, in expect
    resolved = impl._literal_coercion(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\sql\coercions.py", line 621, in _literal_coercion
    return self._text_coercion(element, argname, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\sql\coercions.py", line 614, in _text_coercion
    return _no_text_coercion(element, argname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\sql\coercions.py", line 584, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression 'SELECT qgep_sys.drop_symb...' should be explicitly declared as text('SELECT qgep_sys.drop_symb...')


Version de Python : 3.12.5 (main, Aug  8 2024, 11:21:54) [MSC v.1938 64 bit (AMD64)] 
Version de QGIS : 3.34.10-Prizren Prizren, 113de9e1 

Chemin Python :
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python
C:/Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\Users\pulpoar\AppData\Roaming\Python\Python312\site-packages
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:/Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python
C:\Users\pulpoar\AppData\Roaming\QGIS\QGIS3\profiles\pulpoar\python\plugins\qfieldsync\libqfieldsync.whl
C:/git/QGEP/project
C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
.
```

**To Reproduce**
Exact steps to reproduce the behavior:

**Expected behavior**

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version
 - OS

**Additional context**

**Comment by ponceta** [comment]
https://stackoverflow.com/questions/17972020/how-to-execute-raw-sql-in-flask-sqlalchemy-app

**Comment by sjib** [comment]
I think this should be fixed:
see
https://github.com/search?q=repo%3AQGEP%2Fqgepqwat2ili%20SELECT%20qgep_sys.drop_symb&type=code

and 
https://github.com/QGEP/qgepqwat2ili/blob/6acb01260d098783d612f1f4a9d72cc7e2269476/qgepqwat2ili/qgep/import_.py#L31

@ponceta Are you using and old version of the plugin?

**Comment by ponceta** [comment]
No but I fixed it without closing this in https://github.com/QGEP/qgepqwat2ili/commit/c1d194c138b7d5e5cf8de294802c68bf75b2f312
