### ISSUE TITLE
Missing Project File v12.0.0

### ISSUE THREAD

**Issue by sjib** [qgep/QGEP#869]
**Describe the bug**
_A clear and concise description of what the bug is._

2024-08-30T16:24:28     WARNING    Error transferring https://github.com/QGEP/QGEP/releases/download/v12.0.0/qgep-v12.0.0.zip - server replied: Not Found

**To Reproduce**
Exact steps to reproduce the behavior:
1. Go to 'Datamodel Tool'
2. Click on 'Load QGIS project'
3. See error

**Expected behavior**
_A clear and concise description of what you expected to happen._

Download of project file is supported

**Screenshots / data**
![grafik](https://github.com/user-attachments/assets/0e6e442b-4e00-43de-8eae-fbedf86cce25)

```
2024-08-30T16:24:28     WARNING    Traceback (most recent call last):
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 114, in wrapper
              return func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 915, in load_project
              qgep_path = self._download(url, "qgep.zip")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 352, in _download
              raise QGEPDatamodelError(error_message)
             qgepplugin.gui.qgepdatamodeldialog.QGEPDatamodelError: Error transferring https://github.com/QGEP/QGEP/releases/download/v12.0.0/qgep-v12.0.0.zip - server replied: Not Found
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 116, in wrapper
              args[0]._show_error(str(e))
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 276, in _show_error
              self._done_progress()
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 270, in _done_progress
              self.progress_dialog.close()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: 'NoneType' object has no attribute 'close'
             
```

**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version
 - OS

**Additional context**

**Comment by ponceta** [comment]
Fix commited to master :

https://github.com/QGEP/qgepplugin/commit/c2c26d6af0eb13befef65cecffd31d2732918ad3

There is no v12 since there are no alterations to the QGIS project.

Will be available on next release soon.
