### ISSUE TITLE
INTERLIS export DSS_2015_LV95

### ISSUE THREAD

**Issue by ponceta** [qgep/QGEP#871]
**Describe the bug**
I can't make the INTERLIS export from the qgep demo data even after registering organisations into their subclasses

```
-- Insert Municipalities
INSERT INTO qgep_od.municipality (obj_id)
VALUES 
( 'ch13p7mzOG000003' ),
( 'ch13p7mzOG000004' ),
( 'ch13p7mzOG000002' ),
( 'ch13p7mzOG000005' ),
( 'ch13p7mzOG000006' ),
( 'ch13p7mzOG000007' ),
( 'ch13p7mzOG000008' ),
( 'ch13p7mzOG000009' ),
( 'ch13p7mzOG000010' ),
( 'ch13p7mzOG000011' ),
( 'ch13p7mzOG000012' ),
( 'ch13p7mzOG000013' );

-- Insert Private / unknown
INSERT INTO qgep_od.private (obj_id)
VALUES
( 'ch13p7mzOG000014' ),
( 'ch13p7mzOG000016');

-- Insert wastewater associations
INSERT INTO qgep_od.waste_water_association (obj_id)
VALUES
( 'ch13p7mzOG000015' );
```

```
/* Should AVOID 
ERROR: number of subclass elements of wastewater_structure NOT CORRECT in schema qgep_od: 
Add missing obj_id in wastewater_structure subclasses so that number of subclass elements match wastewater_structure elements. 
See qgep logs tab for details.
*/

/*
Sucess: OK: Integrity checks organisation
*/

```
I have both messages (ERROR AND SUCCESS) but the export is stopped because of the error.

**To Reproduce**
Exact steps to reproduce the behavior:
1. Start QGEP with demo data
2. Click on INTERLIS EXPORT
3. SELECT DSS_2015_LV95

![image](https://github.com/user-attachments/assets/048ec999-1f43-4916-b087-9ab0186c170a)

![image](https://github.com/user-attachments/assets/ee818816-6a1f-4297-891f-95a907f2a54a)

Also QGEP logs is not displaying any additionnal error informations as the message suggest.

**Expected behavior**
INTERLIS export is working when organisation subclasses are set.

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version 1.6.3
 - QGEP datamodel version 1.6.2
 - QGEP project file version 11.0
 - QGIS Version 3.34.X
 - OS

**Additional context**

**Comment by ponceta** [comment]
@sjib any hints on what I miss here?

**Comment by ponceta** [comment]
@sjib here was the issue with subclasses on qgep demo data

**Comment by sjib** [comment]
This function was called and got an Error: 
https://github.com/QGEP/qgepqwat2ili/blob/6acb01260d098783d612f1f4a9d72cc7e2269476/qgepqwat2ili/utils/ili2db.py#L58

You should have more info in the Logger windows:
logger.info(f"Number of {subclass} datasets: {cursor.rowcount}")
            wastewater_structure_count = wastewater_structure_count - cursor.rowcount

**Comment by ponceta** [comment]
```
2024-10-03T11:42:51        qgepplugin:QGEP plugin version dev started
2024-10-03T11:42:51        qgepplugin.utils.translation:Using system default locale: fr_CH
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:INTEGRITY CHECK organisations subclass data...
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of organisation datasets: 15
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of administrative_office datasets: 0
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of waste_water_association datasets: 1
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of municipality datasets: 12
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of canton datasets: 0
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of cooperative datasets: 0
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of private datasets: 2
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of waste_water_treatment_plant datasets: 0
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:OK: number of subclass elements of class organisation OK in schema qgep_od!
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:INTEGRITY CHECK wastewater_structures subclass data...
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of wastewater_structure datasets: 29049
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of manhole datasets: 10897
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of channel datasets: 17597
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of special_structure datasets: 474
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of infiltration_installation datasets: 0
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of discharge_point datasets: 71
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Number of wwtp_structure datasets: 0
2024-10-03T11:43:53        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:ERROR: number of subclass elements of wastewater_structure NOT CORRECT in schema qgep_od: checksum = 10 (positiv number means missing entries, negativ means too many subclass entries)
```

This means that I have 10 wastewater_structures more than expected which have an 'unknow' ws_type :

![image](https://github.com/user-attachments/assets/ecba2943-3195-43f7-95ee-2a25a9541831)

```
-- Remove unrelated wastewater strucures
DELETE FROM qgep_od.vw_qgep_wastewater_structure WHERE obj_id='ch13p7mzWS011963';
DELETE FROM qgep_od.vw_qgep_wastewater_structure WHERE obj_id='ch13p7mzWS020414';
DELETE FROM qgep_od.vw_qgep_wastewater_structure WHERE obj_id='ch13p7mzWS005246';
DELETE FROM qgep_od.vw_qgep_wastewater_structure WHERE obj_id='ch13p7mzWS010030';
DELETE FROM qgep_od.vw_qgep_wastewater_structure WHERE obj_id='ch13p7mzWS020415';
DELETE FROM qgep_od.vw_qgep_wastewater_structure WHERE obj_id='ch13p7mzWS003194';
DELETE FROM qgep_od.vw_qgep_wastewater_structure WHERE obj_id='ch13p7mzWS001711';
DELETE FROM qgep_od.vw_qgep_wastewater_structure WHERE obj_id='ch13p7mzWS023801';
DELETE FROM qgep_od.vw_qgep_wastewater_structure WHERE obj_id='ch13p7mzWS025479';
DELETE FROM qgep_od.vw_qgep_wastewater_structure WHERE obj_id='ch13p7mzWS003195';
```

**Comment by sjib** [comment]
Yes - that is not as it should be and why we have this wastewater_structure subclass check to prevent you from exporting invalid data in a early stage.
Documentation on these checks are here: https://qgep.github.io/docs/fr/admin-guide/interlis-io/index.html#export

**Comment by ponceta** [comment]
Now I have which should also be checked before starting the export.

```
Une erreur est survenue lors de l'exécution du code Python : 

sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « betreiberref » DETAIL:  La ligne en échec contient (15, null, 1800, unbekannt, null, null, AAA KA56777, null, null, null, null, null, unbekannt, null, unbekannt, null, null, null, null, null, null, null). [SQL: INSERT INTO pg2ili_dss.abwasserbauwerk (t_id, akten, baujahr, baulicherzustand, baulos, bemerkung, bezeichnung, bruttokosten, detailgeometrie, ersatzjahr, finanzierung, inspektionsintervall, sanierungsbedarf, standortname, astatus, subventionen, wbw_basisjahr, wbw_bauart, wiederbeschaffungswert, zugaenglichkeit, betreiberref, eigentuemerref) VALUES (%(t_id)s, %(akten)s, %(baujahr)s, %(baulicherzustand)s, %(baulos)s, %(bemerkung)s, %(bezeichnung)s, %(bruttokosten)s, ST_Force2D(NULL), %(ersatzjahr)s, %(finanzierung)s, %(inspektionsintervall)s, %(sanierungsbedarf)s, %(standortname)s, %(astatus)s, %(subventionen)s, %(wbw_basisjahr)s, %(wbw_bauart)s, %(wiederbeschaffungswert)s, %(zugaenglichkeit)s, %(betreiberref)s, %(eigentuemerref)s)] [parameters: {'t_id': 15, 'akten': None, 'baujahr': 1800, 'baulicherzustand': 'unbekannt', 'baulos': None, 'bemerkung': None, 'bezeichnung': 'AAA KA56777', 'bruttokosten': None, 'ersatzjahr': None, 'finanzierung': None, 'inspektionsintervall': None, 'sanierungsbedarf': 'unbekannt', 'standortname': None, 'astatus': 'unbekannt', 'subventionen': None, 'wbw_basisjahr': None, 'wbw_bauart': None, 'wiederbeschaffungswert': None, 'zugaenglichkeit': None, 'betreiberref': None, 'eigentuemerref': None}] (Background on this error at: https://sqlalche.me/e/20/gkpj) 
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « betreiberref »
DETAIL:  La ligne en échec contient (15, null, 1800, unbekannt, null, null, AAA KA56777, null, null, null, null, null, unbekannt, null, unbekannt, null, null, null, null, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 623, in action_do_export
    qgepdss_export(selection=export_dialog.selected_ids, labels_file=labels_file_path, orientation=eorientation)
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepdss\export.py", line 1023, in qgep_export
    abwasser_session.flush()
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1227, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1422, in execute
    return meth(
           ^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\sql\elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1850, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « betreiberref »
DETAIL:  La ligne en échec contient (15, null, 1800, unbekannt, null, null, AAA KA56777, null, null, null, null, null, unbekannt, null, unbekannt, null, null, null, null, null, null, null).

[SQL: INSERT INTO pg2ili_dss.abwasserbauwerk (t_id, akten, baujahr, baulicherzustand, baulos, bemerkung, bezeichnung, bruttokosten, detailgeometrie, ersatzjahr, finanzierung, inspektionsintervall, sanierungsbedarf, standortname, astatus, subventionen, wbw_basisjahr, wbw_bauart, wiederbeschaffungswert, zugaenglichkeit, betreiberref, eigentuemerref) VALUES (%(t_id)s, %(akten)s, %(baujahr)s, %(baulicherzustand)s, %(baulos)s, %(bemerkung)s, %(bezeichnung)s, %(bruttokosten)s, ST_Force2D(NULL), %(ersatzjahr)s, %(finanzierung)s, %(inspektionsintervall)s, %(sanierungsbedarf)s, %(standortname)s, %(astatus)s, %(subventionen)s, %(wbw_basisjahr)s, %(wbw_bauart)s, %(wiederbeschaffungswert)s, %(zugaenglichkeit)s, %(betreiberref)s, %(eigentuemerref)s)]
[parameters: {'t_id': 15, 'akten': None, 'baujahr': 1800, 'baulicherzustand': 'unbekannt', 'baulos': None, 'bemerkung': None, 'bezeichnung': 'AAA KA56777', 'bruttokosten': None, 'ersatzjahr': None, 'finanzierung': None, 'inspektionsintervall': None, 'sanierungsbedarf': 'unbekannt', 'standortname': None, 'astatus': 'unbekannt', 'subventionen': None, 'wbw_basisjahr': None, 'wbw_bauart': None, 'wiederbeschaffungswert': None, 'zugaenglichkeit': None, 'betreiberref': None, 'eigentuemerref': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

**Comment by sjib** [comment]
We could make a similar check as with the [def check_identifier_null():](https://github.com/QGEP/qgepqwat2ili/blob/6acb01260d098783d612f1f4a9d72cc7e2269476/qgepqwat2ili/utils/ili2db.py#L101) for this

- [x] betreiberref
- [x] eigentuemerref 

will be MANDATORY in VSA-DSS / SIA405 Abwasserr

Are there more?

**Comment by sjib** [comment]
@ponceta 
This is mentioned in step 3  of the [Preparation for migration QGEP -> TEKSI Wastewater & GEP](https://github.com/teksi/wastewater/discussions/437) that you have to check for empty refs

**Comment by ponceta** [comment]
> We could make a similar check as with the [def check_identifier_null():](https://github.com/QGEP/qgepqwat2ili/blob/6acb01260d098783d612f1f4a9d72cc7e2269476/qgepqwat2ili/utils/ili2db.py#L101) for this
> 
> * [ ]  betreiberref
> * [ ]  eigentuemerref
> 
> will be MANDATORY in VSA-DSS / SIA405 Abwasserr
> 
> Are there more?

Indeed, and maybe for the future a button to check validity if it is not constrainted by the datamodel!

**Comment by sjib** [comment]
Also added 
- [x] datenherrref
- [x] datenlieferantref
to comply with Release 2020.xx requirements
