### ISSUE TITLE
name 'rollback_session' is not defined

### ISSUE THREAD

**Issue by sjib** [qgep/QGEP#873]
**Describe the bug**

**To Reproduce**
Exact steps to reproduce the behavior:
1. Go to 'INTERLIS Import'
2. Select import xtf transferdatensatz_sia405_abwasser_2015_d_LV95_20210517.xtf
3. Click Import

Ein Fehler trat bei der Ausführung von Python-Code auf: 

NameError: name 'rollback_session' is not defined. Did you mean: 'self.rollback_session'? 
Traceback (most recent call last):
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: FEHLER:  doppelter Schlüsselwert verletzt Unique-Constraint »pkey_qgep_od_wastewater_structure_obj_id«
DETAIL:  Schlüssel »(obj_id)=(ch080qwzAW001080)« existiert bereits.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu2/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\gui_import.py", line 224, in commit_session
    self.session.commit()
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\session.py", line 1046, in commit
    self.transaction.commit()
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\session.py", line 504, in commit
    self._prepare_impl()
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\session.py", line 483, in _prepare_impl
    self.session.flush()
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\session.py", line 2540, in flush
    self._flush(objects)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\session.py", line 2681, in _flush
    with util.safe_reraise():
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\session.py", line 2642, in _flush
    flush_context.execute()
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\unitofwork.py", line 419, in execute
    n.execute_aggregate(self, set_)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\unitofwork.py", line 697, in execute_aggregate
    persistence.save_obj(
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\persistence.py", line 1131, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) FEHLER:  doppelter Schlüsselwert verletzt Unique-Constraint »pkey_qgep_od_wastewater_structure_obj_id«
DETAIL:  Schlüssel »(obj_id)=(ch080qwzAW001080)« existiert bereits.

[SQL: INSERT INTO qgep_od.wastewater_structure (obj_id, accessibility, contract_section, detail_geometry_geometry, financing, gross_costs, identifier, inspection_interval, location_name, records, remark, renovation_necessity, replacement_value, rv_base_year, rv_construction_type, status, structure_condition, subsidies, year_of_construction, year_of_replacement, last_modification, fk_dataowner, fk_provider, fk_owner, fk_operator, _usage_current, _function_hierarchic, _label, fk_main_cover, _depth, fk_main_wastewater_node, _cover_label, _input_label, _output_label, _bottom_label) VALUES (%(obj_id)s, %(accessibility)s, %(contract_section)s, ST_Force3D(ST_GeomFromEWKB(%(ST_GeomFromEWKB_1)s)), %(financing)s, %(gross_costs)s, %(identifier)s, %(inspection_interval)s, %(location_name)s, %(records)s, %(remark)s, %(renovation_necessity)s, %(replacement_value)s, %(rv_base_year)s, %(rv_construction_type)s, %(status)s, %(structure_condition)s, %(subsidies)s, %(year_of_construction)s, %(year_of_replacement)s, %(last_modification)s, %(fk_dataowner)s, %(fk_provider)s, %(fk_owner)s, %(fk_operator)s, %(_usage_current)s, %(_function_hierarchic)s, %(_label)s, %(fk_main_cover)s, %(_depth)s, %(fk_main_wastewater_node)s, %(_cover_label)s, %(_input_label)s, %(_output_label)s, %(_bottom_label)s)]
[parameters: {'obj_id': 'ch080qwzAW001080', 'accessibility': 3445, 'contract_section': 'Los 5', 'ST_GeomFromEWKB_1': , 'financing': 5510, 'gross_costs': Decimal('100000.00'), 'identifier': 'VB1', 'inspection_interval': Decimal('2.00'), 'location_name': 'Aletsch', 'records': None, 'remark': None, 'renovation_necessity': 2, 'replacement_value': Decimal('0.00'), 'rv_base_year': 1980, 'rv_construction_type': 4603, 'status': 8493, 'structure_condition': 3037, 'subsidies': Decimal('57000.00'), 'year_of_construction': 1980, 'year_of_replacement': 2008, 'last_modification': datetime.date(2020, 2, 26), 'fk_dataowner': None, 'fk_provider': None, 'fk_owner': 'ch080qwzAR001075', 'fk_operator': 'ch080qwzAV000007', '_usage_current': None, '_function_hierarchic': None, '_label': None, 'fk_main_cover': None, '_depth': None, 'fk_main_wastewater_node': None, '_cover_label': None, '_input_label': None, '_output_label': None, '_bottom_label': None}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu2/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\gui_import.py", line 227, in commit_session
    rollback_session()
    ^^^^^^^^^^^^^^^^
NameError: name 'rollback_session' is not defined. Did you mean: 'self.rollback_session'?

Python-Version: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.34.8-Prizren Prizren, 91642333 

Python-Pfad:
C:/PROGRA~1/QGIS 3.34.8/apps/qgis-ltr/./python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu2/python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu2/python/plugins
C:/PROGRA~1/QGIS 3.34.8/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS 3.34.8\apps\grass\grass83\etc\python
C:\Users\Stefan\Documents
C:\Program Files\QGIS 3.34.8\bin\python312.zip
C:\PROGRA~1\QGIS 3.34.8\apps\Python312\DLLs
C:\PROGRA~1\QGIS 3.34.8\apps\Python312\Lib
C:\Program Files\QGIS 3.34.8\bin
C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages
C:\PROGRA~1\QGIS 3.34.8\apps\Python312
C:\PROGRA~1\QGIS 3.34.8\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS 3.34.8\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS 3.34.8\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.34.8\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu2/python
C:/Daten/QGEP/testing163neu2/20241002_qgep-v11.0.0/project
C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu2/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu2/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
.

**Expected behavior**

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version 1.6.3
 - QGEP datamodel version 1.6.2
 - QGEP project file version 11.0
 - QGIS Version 3.34.8
 - OS Windows 10
 - Postgres 15

**Additional context**
Duplicate error is because I re-imported the same data. But that is not the issue here.

**Comment by sjib** [comment]
@domi4484 NameError: name 'rollback_session' is not defined. Did you mean: 'self.rollback_session'?

Can you check about this?
Is this caused by your recent developments?

**Comment by domi4484** [comment]
> Traceback (most recent call last):
> File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu2/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\gui_import.py", line 227, in commit_session
> rollback_session()
> ^^^^^^^^^^^^^^^^
> NameError: name 'rollback_session' is not defined. Did you mean: 'self.rollback_session'?

@sjib I did only very small changes (the pr about ILI upgrade is still WIP) and never touched that logic.

Is it possible that you have some local modification or are working with an older version? Because if I look at `gui_import.py", line 227` there is nothing with rollback. It is at line 233

**Comment by sjib** [comment]
Similar error on INTERLIS Import VSA-DSS 2015

```
Ein Fehler trat bei der Ausführung von Python-Code auf: 

AttributeError: 'GuiImport' object has no attribute 'rollback_session' 
Traceback (most recent call last):
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu2/python/plugins\qgepplugin\qgepplugin.py", line 539, in actionImportClicked
    action_import(self)
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu2/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 174, in action_import
    import_dialog = GuiImport(plugin.iface.mainWindow())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testing163neu2/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\gui_import.py", line 35, in __init__
    self.rejected.connect(self.rollback_session)
                          ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GuiImport' object has no attribute 'rollback_session'


Python-Version: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.34.8-Prizren Prizren, 91642333 
```
