### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 122: invalid continuation byte 

### ISSUE THREAD

**Issue by ponceta** [qgep/QGEP#879]
**Describe the bug**
Recuring error message on the datamodel tool :

```
Une erreur est survenue lors de l'exécution du code Python : 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 122: invalid continuation byte 
Traceback (most recent call last):
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 632, in check_version
    current_version = self._get_current_version()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 379, in _get_current_version
    pum_info = self._run_cmd(
               ^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 328, in _run_cmd
    raise QGEPDatamodelError(message)
qgepplugin.gui.qgepdatamodeldialog.QGEPDatamodelError: Could not get current version, are you sure the database is accessible ?
Command :
python3 -m pum info -p pg_port -t qgep_sys.pum_info -d C:\Users\pulpoar\AppData\Local\Temp\QGEP\datamodel-init\datamodel-1.6.2\delta

Output :
'utf-8' codec can't decode byte 0xe9 in position 122: invalid continuation byte


Error :
None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 113, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 459, in switch_datamodel
    self.check_version()
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 113, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 640, in check_version
    self._run_sql(
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 284, in _run_sql
    conn = psycopg2.connect(connection_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pulpoar\AppData\Roaming\Python\Python312\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 122: invalid continuation byte
```
**To Reproduce**
Exact steps to reproduce the behavior:

**Expected behavior**

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version latest
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version
 - OS

**Additional context**

**Comment by sjib** [comment]
to do improve user feedback on this kind of error

**Comment by sjib** [comment]
see also https://github.com/QGEP/QGEP/issues/877
