### ISSUE TITLE
Datamodel and qgepqwat2ili issues for release Datamodel 1.6.2 / Plugin 1.6.4

### ISSUE THREAD

**Issue by sjib** [qgep/QGEP#880]
- [ ] Pull requests to consider from /datamodel: https://github.com/QGEP/datamodel/pulls
- [ ] [qgepqwat2ili issues for this milestone](https://github.com/QGEP/qgepqwat2ili/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Datamodel+1.6.3+Plugin+1.6.4%22)

**Comment by urskaufmann** [comment]
Thanks for plugin 1.6.4.
Testing exports (these was blocking me in the last days):
Export DSS_2015, no selection: no errors in the validation at the end, reachpoints are now exported with Abwassernetzelementref. 
Strange message while exporting:
_2024-10-17T18:46:54     SUCCESS    Sucess : OK: Integrity checks organisation
2024-10-17T18:46:54     SUCCESS    Sucess : OK: Integrity checks wastewater_structure
2024-10-17T18:46:54     SUCCESS    Sucess : OK: Integrity checks identifiers not isNull
2024-10-17T18:46:55     SUCCESS    Sucess : OK: Integrity checks fk_owner not isNull
2024-10-17T18:46:55     SUCCESS    Sucess : OK: Integrity checks fk_operator not isNull
2024-10-17T18:46:55     INFO    INFO: Missing fk_dataowner in schema qgep_od : Add missing fk_dataowner to get a valid INTERLIS export file when converting to Release 2020 (will bei MANDATORY). See qgep logs tab for details.
2024-10-17T18:46:55     INFO    INFO: Missing fk_provider in schema qgep_od : Add missing fk_provider to get a valid INTERLIS export file when converting to Release 2020 (will bei MANDATORY). See qgep logs tab for details.
2024-10-17T18:50:40     SUCCESS    Sucess : Data successfully exported to P:/Thun/Gemeinden/166-167 Unterlangenegg/qgep/exporte/qgep-export2024-10-17_
First SUCCESS OK, then Info about missing fk_dataowner. I checked the XTF-File: there are as many <Datenherr> as records exported, so I think this Info is fake

**Comment by urskaufmann** [comment]
Next test: Export with SIA405, no selection: The same error as till now: I have ARA-Bauwerk-Records in my database, the wastewater-nodes go into the export, but the wastewater_structure can not be found, because ARA-Bauwerk is not part of the SIA405 model.

Gives this error:
Ein Fehler trat bei der Ausführung von Python-Code auf: 

sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "abwassernetzelement" violates foreign key constraint "abwassernetzelement_abwasserbauwerkref_fkey" DETAIL:  Key (abwasserbauwerkref)=(6157) is not present in table "abwasserbauwerk". (Background on this error at: http://sqlalche.me/e/13/gkpj) 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
    dbapi_connection.commit()
psycopg2.errors.ForeignKeyViolation: insert or update on table "abwassernetzelement" violates foreign key constraint "abwassernetzelement_abwasserbauwerkref_fkey"
DETAIL:  Key (abwasserbauwerkref)=(6157) is not present in table "abwasserbauwerk".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 715, in action_do_export
    qgepsia405_export(
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepsia405\export.py", line 1196, in qgep_export
    abwasser_session.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 1046, in commit
    self.transaction.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 508, in commit
    t[1].commit()
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1762, in commit
    self._do_commit()
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1793, in _do_commit
    self.connection._commit_impl()
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 773, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "abwassernetzelement" violates foreign key constraint "abwassernetzelement_abwasserbauwerkref_fkey"
DETAIL:  Key (abwasserbauwerkref)=(6157) is not present in table "abwasserbauwerk".

(Background on this error at: http://sqlalche.me/e/13/gkpj)


Python-Version: 3.12.6 (main, Sep  7 2024, 18:59:42) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.34.10-Prizren Prizren, 113de9e1

**Comment by urskaufmann** [comment]
Next test: SIA405 with selection (select all reaches and all structures exept this ARA-Bauwerke): OK, same Info about missing fk_dataowner after success OK as in the DSS-export.

**Comment by urskaufmann** [comment]
Next test: SIA405 with selection, selection stops at Blindanschluss without node: Success, no errors, jus these notes...

Next test: DSS with selection, selection stops at Blindanschluss without node: Error!! Very Strange (tww_od!)
Ein Fehler trat bei der Ausführung von Python-Code auf: 

AttributeError: model_classes_tww_od 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\util\_collections.py", line 210, in __getattr__
    return self._data[key]
           ~~~~~~~~~~^^^^^
KeyError: 'model_classes_tww_od'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 724, in action_do_export
    qgepdss_export(
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepdss\export.py", line 3012, in qgep_export
    QGEP.model_classes_tww_od.waste_water_treatment_plant,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\util\_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: model_classes_tww_od


Python-Version: 3.12.6 (main, Sep  7 2024, 18:59:42) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.34.10-Prizren Prizren, 113de9e1 

Python-Pfad:
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3\apps\grass\grass84\etc\python
C:\
C:\Program Files\QGIS3\bin\python312.zip
C:\PROGRA~1\QGIS3\apps\Python312\DLLs
C:\PROGRA~1\QGIS3\apps\Python312\Lib
C:\Program Files\QGIS3\bin
C:\PROGRA~1\QGIS3\apps\Python312
C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python
C:\Users\KAU\AppData\Roaming\QGIS\QGIS3\profiles\qgep161_prerealise\python\plugins\qfieldsync\libqfieldsync.whl
P:/Thun/Gemeinden/166-167 Unterlangenegg/qgep
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..

**Comment by urskaufmann** [comment]
other thing: when installing just the plugin 1.6.4 in my qgep-environement, I get the error:
2024-10-17T18:45:10     CRITICAL    Error : Could not load qgepqwat2ili due to unmet dependencies. See logs for more details.
  qgepplugin:No module named 'QgisModelBaker.libs.modelbaker'

I did then install the actual modelbaker plugin (7.9.3) and then it was ok. (I had still 7.0.3 before). Important to know!

**Comment by ponceta** [comment]
Wow, that's a real complete and quick feedback, thank you @urskaufmann.

I caught a logging error on qgepqwat2ili which can cause a system overflow :

```
INFO     Start Exporting DSS_2015_LV95 - qgepdss_export
INFO     print filtered 'False'
INFO     print subset_ids '[]'
INFO     get list of id's of class wwtp_structure (ARABauwerk)...
INFO      row[0] = ch13p7mzMA010492
INFO      building up '['ch13p7mzMA010492']' ...
INFO      row[0] = ch13p7mzMA002320
INFO      building up '['ch13p7mzMA010492', 'ch13p7mzMA002320']' ...
INFO      row[0] = ch13p7mzCL001634
INFO      building up '['ch13p7mzMA010492', 'ch13p7mzMA002320', 'ch13p7mzCL001634']' ...
INFO      row[0] = ch13p7mzMA007444
INFO      building up '['ch13p7mzMA010492', 'ch13p7mzMA002320', 'ch13p7mzCL001634', 'ch13p7mzMA007444']' ...
INFO      row[0] = ch13p7mzCL000056
INFO      building up '['ch13p7mzMA010492', 'ch13p7mzMA002320', 'ch13p7mzCL001634', 'ch13p7mzMA007444', 'ch13p7mzCL000056']' ...
INFO      row[0] = ch13p7mzCL004308
INFO      building up '['ch13p7mzMA010492', 'ch13p7mzMA002320', 'ch13p7mzCL001634', 'ch13p7mzMA007444', 'ch13p7mzCL000056', 'ch13p7mzCL004308']' ...
INFO      row[0] = ch13p7mzCL013469
INFO      building up '['ch13p7mzMA010492', 'ch13p7mzMA002320', 'ch13p7mzCL001634', 'ch13p7mzMA007444', 'ch13p7mzCL000056', 'ch13p7mzCL004308', 'ch13p7mzCL013469']' ...
INFO      row[0] = ch13p7mzCL001067
INFO      building up '['ch13p7mzMA010492', 'ch13p7mzMA002320', 'ch13p7mzCL001634', 'ch13p7mzMA007444', 'ch13p7mzCL000056', 'ch13p7mzCL004308', 'ch13p7mzCL013469', 'ch13p7mzCL001067']' ...
INFO      row[0] = ch13p7mzCL010684
...
```

This has to be fixed urgently otherwise we will face some user issues.

I had several 8 Go Logs files in a few minutes.

**Comment by ponceta** [comment]
I check with @domi4484 how to set a log only when debug parameter is activated.

**Comment by sjib** [comment]
@ponceta We can take out again this logger printing - I just added it to be able to see what happens during debugging. 
May be we want to keep it for the moment as there are still some issues.

But it would be a nice new option if depending on how I set the the log level we can print logger messages.

**Comment by ponceta** [comment]
As @urskaufmann said, it seems that provided ilitools binaries are not used?

![image](https://github.com/user-attachments/assets/824522af-169b-4e01-8c17-e61bfd937a89)

**Comment by sjib** [comment]
> I check with @domi4484 how to set a log only when debug parameter is activated.

Pull request to implement this - https://github.com/QGEP/qgepqwat2ili/pull/170/files
