### ISSUE TITLE
Export Selection of reaches and wastewater structures fails

### ISSUE THREAD

**Issue by ponceta** [qgep/QGEP#881]
**Describe the bug**
Export Selection of reaches and wastewater structures fails :

![image](https://github.com/user-attachments/assets/98ebbbf2-549f-476a-acf2-3c76a42f89b5)

```
sqlalchemy.exc.ArgumentError: ON clause, typically a SQL expression or ORM relationship attribute expected, got . 
Traceback (most recent call last):
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 605, in actionExportClicked
    self.interlisImporterExporter.action_export()
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 149, in action_export
    raise exception
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 119, in action_export
    self.interlis_importer_exporter.interlis_export(
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 198, in interlis_export
    self._export_to_intermediate_schema(
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 366, in _export_to_intermediate_schema
    twwInterlisExporter.tww_export()
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 88, in tww_export
    raise exception
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 83, in tww_export
    self._export()
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 98, in _export
    self._export_sia405_abwasser()
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 212, in _export_sia405_abwasser
    self._export_dryweather_downspout()
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 826, in _export_dryweather_downspout
    query = query.join(
            ^^^^^^^^^^^
  File "", line 2, in join
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\sql\base.py", line 280, in _generative
    x = fn(self, *args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^
  File "", line 2, in join
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\orm\base.py", line 304, in generate
    fn(self, *args, **kw)
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\orm\query.py", line 2429, in join
    onclause_element = coercions.expect(
                       ^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\sql\coercions.py", line 396, in expect
    resolved = impl._literal_coercion(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\sql\coercions.py", line 899, in _literal_coercion
    self._raise_for_expected(element)
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\sqlalchemy\sql\coercions.py", line 518, in _raise_for_expected
    raise exc.ArgumentError(msg, code=code) from err
sqlalchemy.exc.ArgumentError: ON clause, typically a SQL expression or ORM relationship attribute expected, got .
```

**To Reproduce**
Export Selection to DSS 
1. Select some connected reaches and wastewater structures
2. Click on export
3. Click on limit to selection

**Expected behavior**
A selection can be easily exported

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version
 - OS

**Additional context**

**Comment by ponceta** [comment]
https://github.com/teksi/wastewater/issues/463 issue is here

**Comment by sjib** [comment]
Wrong selection criteria for` _export_dryweather_downspout`
