### ISSUE TITLE
Check identifier Check leaves plugin in a bad state if it fails.

### ISSUE THREAD

**Issue by ponceta** [qgep/QGEP#882]
**Describe the bug**
check_identifier_null seems to have failed on my data. But it should have failed in a less messy way.

```
TypeError: 'NoneType' object is not subscriptable 
Traceback (most recent call last):
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 470, in action_do_export
    check_identifier = check_identifier_null()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\utils\ili2db.py", line 169, in check_identifier_null
    cursor.fetchone()[0]
    ~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**To Reproduce**
Exact steps to reproduce the behavior:

**Expected behavior**

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version
 - OS

**Additional context**

**Comment by sjib** [comment]
- [ ] to fix also on tww if ok
